import { StyleSheet } from 'react-native';
import { Colors } from '@/constants/Colors';

export const s = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8F9FA' },
  center: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  headerBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
  },
  headerTitle: { fontSize: 15, fontWeight: '700', color: '#1a3a52' },
  newBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#1a3a52',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
  },
  newBtnText: { color: '#fff', fontWeight: '700', fontSize: 13 },
  testCard: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 16,
    marginHorizontal: 16,
    marginBottom: 10,
    elevation: 2,
  },
  testHeader: { flexDirection: 'row', alignItems: 'flex-start', gap: 10 },
  statusDot: { width: 10, height: 10, borderRadius: 5, marginTop: 4 },
  testInfo: { flex: 1 },
  testName: { fontSize: 14, fontWeight: '700', color: '#1a3a52' },
  testDesc: { fontSize: 12, color: '#6B7280', marginTop: 2 },
  testActions: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  winnerBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#FEF3C7',
    borderRadius: 8,
    padding: 8,
    marginTop: 10,
  },
  winnerText: { fontSize: 13, fontWeight: '700', color: '#92400E' },
  variantsSection: { marginTop: 12, paddingTop: 12, borderTopWidth: 1, borderTopColor: '#F3F4F6' },
  metricLabel: { fontSize: 12, color: '#6B7280', marginBottom: 10 },
  variantRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 10,
    marginBottom: 6,
    backgroundColor: '#F9FAFB',
  },
  variantRowWinner: { backgroundColor: '#FEF9C3' },
  variantLeft: { flexDirection: 'row', alignItems: 'center', flex: 1 },
  variantName: { fontSize: 13, fontWeight: '600', color: '#1a3a52', flex: 1 },
  variantTraffic: { fontSize: 11, color: '#9CA3AF' },
  variantRight: { alignItems: 'flex-end' },
  variantConvRate: { fontSize: 16, fontWeight: '800', color: '#1a3a52' },
  variantCount: { fontSize: 11, color: '#9CA3AF' },
  dateMeta: { fontSize: 11, color: '#9CA3AF', marginTop: 8 },

  // Modal styles
  modalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0,0,0,0.45)',
  },
  modalSheet: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    maxHeight: '90%',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  modalTitle: { fontSize: 18, fontWeight: '700', color: '#1a3a52' },
  mGroup: { marginBottom: 16 },
  mLabel: { fontSize: 13, fontWeight: '600', color: '#374151', marginBottom: 6 },
  mLabelSmall: { fontSize: 12, fontWeight: '500', color: '#6B7280', marginBottom: 4 },
  mRequired: { color: '#EF4444' },
  mInput: {
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    color: '#111827',
    backgroundColor: '#F9FAFB',
  },
  mInputErr: { borderColor: '#EF4444', backgroundColor: '#FEF2F2' },
  mErrText: { fontSize: 11, color: '#EF4444', marginTop: 4 },
  mHelper: { fontSize: 11, color: '#9CA3AF', marginTop: 3 },
  variantInputRow: { flexDirection: 'row' },
  modalActions: {
    flexDirection: 'row',
    gap: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#F3F4F6',
  },
  mBtn: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mBtnCancel: { backgroundColor: '#F3F4F6' },
  mBtnCancelText: { fontWeight: '600', color: '#374151' },
  mBtnCreate: { backgroundColor: '#1a3a52' },
  mBtnCreateText: { fontWeight: '700', color: '#fff' },
});
