import { StyleSheet } from 'react-native';
import { Colors } from '@/constants/Colors';

export const s = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8F9FA' },
  center: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    margin: 16,
    padding: 12,
    backgroundColor: '#EFF6FF',
    borderRadius: 12,
  },
  headerText: { flex: 1, fontSize: 13, color: '#1E40AF' },
  // NIDHI: governance — bulk action buttons
  bulkActionRow: { flexDirection: 'row', gap: 10, paddingHorizontal: 16, marginBottom: 16 },
  bulkButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
  },
  bulkEnableBtn: { backgroundColor: '#EFF6FF', borderColor: '#22C55E' },
  bulkDisableBtn: { backgroundColor: '#FEE2E2', borderColor: '#EF4444' },
  bulkButtonText: { fontSize: 13, fontWeight: '600', color: '#1a3a52' },
  bulkButtonDisabled: { opacity: 0.5 },
  ruleCard: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 16,
    marginHorizontal: 16,
    marginBottom: 10,
    elevation: 2,
  },
  ruleCardDisabled: { opacity: 0.5 },
  ruleTop: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 10 },
  severityBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 6 },
  severityText: { fontSize: 11, fontWeight: '700' },
  ruleName: { flex: 1, fontSize: 14, fontWeight: '700', color: '#1a3a52' },
  ruleMetric: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 4,
    marginBottom: 8,
  },
  metricLabel: { fontSize: 12, color: '#6B7280' },
  metricValue: { fontSize: 12, color: '#374151', fontFamily: 'monospace', fontWeight: '600' },
  thresholdValue: { fontSize: 14, fontWeight: '800', color: '#1a3a52' },
  editRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  thresholdInput: {
    borderWidth: 1,
    borderColor: '#1a3a52',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 4,
    fontSize: 14,
    minWidth: 80,
  },
  saveBtn: {
    backgroundColor: '#1a3a52',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  saveBtnText: { color: '#fff', fontSize: 12, fontWeight: '700' },
  cancelBtn: { paddingHorizontal: 8 },
  cancelBtnText: { color: '#6B7280', fontSize: 12 },
  ruleMeta: { marginBottom: 8 },
  metaSmall: { fontSize: 11, color: '#9CA3AF' },
  channelRow: { flexDirection: 'row', gap: 8, flexWrap: 'wrap' },
  channelChip: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    backgroundColor: '#F3F4F6',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  channelChipActive: { backgroundColor: '#EFF6FF', borderColor: '#1a3a52' },
  channelChipText: { fontSize: 11, color: '#9CA3AF' },
  channelChipTextActive: { color: '#1a3a52', fontWeight: '600' },
  errorContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 48,
    paddingHorizontal: 32,
    marginHorizontal: 16,
    backgroundColor: '#fff',
    borderRadius: 16,
    gap: 12,
  },
  errorTitle: { fontSize: 16, fontWeight: '700', color: '#1a3a52', textAlign: 'center' },
  errorMessage: { fontSize: 13, color: '#6B7280', textAlign: 'center', lineHeight: 18 },
  retryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#1a3a52',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 8,
    marginTop: 8,
  },
  retryButtonText: { color: '#fff', fontSize: 14, fontWeight: '600' },
});
