import { StyleSheet } from 'react-native';
import { Colors } from '@/constants/Colors';

export const s = StyleSheet.create({
  container: { flex: 1 },
  scrollContent: { paddingBottom: 40 },
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', gap: 12 },
  loadingText: { fontSize: 14 },

  // Header
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 12,
  },
  backBtn: { padding: 4 },
  headerTitle: { fontSize: 18, fontWeight: '700', color: '#fff' },
  headerSub: { fontSize: 12, color: 'rgba(255,255,255,0.8)', marginTop: 1 },
  headerRefreshBtn: { marginLeft: 'auto', padding: 4 },

  // Error Banner
  errorBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginHorizontal: 16,
    marginTop: 12,
    padding: 12,
    borderRadius: 10,
  },
  errorBannerText: { fontSize: 13, flex: 1 },

  // Section
  section: { paddingHorizontal: 16, marginTop: 20 },
  sectionTitle: { fontSize: 16, fontWeight: '700', marginBottom: 12 },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  viewAllLink: { fontSize: 13, fontWeight: '600' },

  // Overview Grid
  overviewGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  overviewCard: {
    width: '47.5%',
    borderRadius: 14,
    padding: 14,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  cardIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  cardValue: { fontSize: 18, fontWeight: '700', marginBottom: 2 },
  cardTitle: { fontSize: 12, textAlign: 'center', marginBottom: 2 },
  cardSubtitle: { fontSize: 11, textAlign: 'center' },

  // Bar Chart
  chartCard: {
    borderRadius: 14,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  barChart: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    height: 120,
    marginBottom: 12,
  },
  barColumn: { flex: 1, alignItems: 'center', gap: 4, height: '100%', justifyContent: 'flex-end' },
  barTopLabel: { fontSize: 9, fontWeight: '600', marginBottom: 2 },
  barTrack: {
    width: '60%',
    height: 70,
    backgroundColor: '#f3f4f6',
    borderRadius: 4,
    justifyContent: 'flex-end',
    overflow: 'hidden',
  },
  barFill: { width: '100%', borderRadius: 4 },
  barBottomLabel: { fontSize: 9, marginTop: 4 },
  growthSummary: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    borderTopWidth: 1,
    borderTopColor: '#f3f4f6',
    paddingTop: 12,
    marginTop: 4,
  },
  growthSummaryItem: { alignItems: 'center' },
  growthLabel: { fontSize: 11, marginBottom: 2 },
  growthValue: { fontSize: 16, fontWeight: '700' },
  emptyChart: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 36,
    gap: 8,
  },
  emptyChartText: { fontSize: 13 },
  emptyChartSubText: { fontSize: 11, marginTop: 2, textAlign: 'center' as const },

  // List Card
  listCard: {
    borderRadius: 14,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  emptyListRow: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 28,
    gap: 8,
  },
  emptyListText: { fontSize: 13 },

  // Merchants
  merchantRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 10,
  },
  rankBadge: {
    width: 32,
    height: 32,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  rankText: { fontSize: 12, fontWeight: '700' },
  merchantInfo: { flex: 1 },
  merchantName: { fontSize: 14, fontWeight: '600', marginBottom: 2 },
  merchantCategory: { fontSize: 12 },
  merchantRevenue: { fontSize: 14, fontWeight: '700' },

  // Suspicious Activity
  cleanCard: {
    borderRadius: 14,
    padding: 28,
    alignItems: 'center',
    gap: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  cleanText: { fontSize: 15, fontWeight: '600' },
  cleanSub: { fontSize: 13 },
  suspiciousRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 10,
  },
  severityDot: { width: 8, height: 8, borderRadius: 4, marginTop: 4 },
  suspiciousInfo: { flex: 1 },
  suspiciousTypeRow: { marginBottom: 4 },
  typeBadge: { paddingHorizontal: 8, paddingVertical: 2, borderRadius: 6, alignSelf: 'flex-start' },
  typeText: { fontSize: 11, fontWeight: '600', textTransform: 'capitalize' },
  suspiciousDesc: { fontSize: 13, lineHeight: 18, marginBottom: 4 },
  suspiciousTime: { fontSize: 11 },

  // Platform Revenue Trend
  platformRevenueRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#f3f4f6',
    marginBottom: 14,
  },
  platformRevenueStat: { alignItems: 'center' },
  platformRevenueValue: { fontSize: 16, fontWeight: '700', marginBottom: 2 },
  platformRevenueLabel: { fontSize: 11 },
  platformTrendBars: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    height: 60,
    gap: 2,
  },
  trendBarCol: { flex: 1, height: '100%', justifyContent: 'flex-end' },
  trendBarTrack: {
    width: '100%',
    height: '100%',
    backgroundColor: '#f3f4f6',
    borderRadius: 3,
    justifyContent: 'flex-end',
    overflow: 'hidden',
  },
  trendBarFill: { width: '100%', borderRadius: 3 },

  // Shortcuts
  shortcutsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  shortcutCard: {
    width: '30%',
    borderRadius: 12,
    padding: 12,
    alignItems: 'center',
    gap: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 3,
    elevation: 2,
  },
  shortcutIcon: {
    width: 40,
    height: 40,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  shortcutLabel: { fontSize: 11, fontWeight: '600', textAlign: 'center' },
});
