import { StyleSheet } from 'react-native';
import { Colors } from '@/constants/Colors';

export const campaignStyles = StyleSheet.create({
  container: { flex: 1 },
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },

  // Header
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  headerTitle: { fontSize: 24, fontWeight: '700' },
  headerSubtitle: { fontSize: 13, marginTop: 2 },
  createBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 10,
    gap: 6,
  },
  createBtnText: { color: Colors.light.card, fontWeight: '600', fontSize: 14 },

  // Search
  searchFilterContainer: { paddingHorizontal: 16, marginBottom: 12 },
  searchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 10,
    gap: 8,
  },
  searchInput: { flex: 1, fontSize: 14, padding: 0 },

  // Tabs
  tabsWrapper: { marginBottom: 12 },
  tabsContent: { paddingHorizontal: 16, gap: 8 },
  tabItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    gap: 6,
  },
  tabLabel: { fontSize: 13, fontWeight: '600' },

  // Campaign Card
  listContent: { paddingHorizontal: 16, paddingBottom: 16 },

  // Empty state
  emptyContainer: { paddingVertical: 60, alignItems: 'center' },
  emptyTitle: { fontSize: 18, fontWeight: '600', marginTop: 16 },
  emptyText: { fontSize: 14, marginTop: 4 },
  retryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 10,
    marginTop: 16,
  },

  // Modal
  modalContainer: { flex: 1 },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
  },
  modalCloseBtn: { padding: 4 },
  modalTitle: { fontSize: 17, fontWeight: '600' },
  modalSaveBtn: { paddingHorizontal: 16, paddingVertical: 8, borderRadius: 8 },
  modalSaveBtnText: { color: Colors.light.card, fontWeight: '600', fontSize: 14 },
  formScroll: { flex: 1 },
  formContent: { padding: 16, paddingBottom: 40 },
  formGroup: { marginBottom: 16 },
  formLabel: { fontSize: 13, fontWeight: '600', marginBottom: 6 },
  formInput: { borderRadius: 10, borderWidth: 1, padding: 12, fontSize: 14 },
  textArea: { minHeight: 80, textAlignVertical: 'top' },
  formRow: { flexDirection: 'row' },

  // Date Range Section
  dateRangeSection: {
    marginBottom: 16,
    padding: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderStyle: 'dashed',
  },
  dateRangeTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 14 },
  dateRangeTitle: { fontSize: 15, fontWeight: '600' },
  dateTimeRow: { flexDirection: 'row', gap: 10 },
  datePickerBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderRadius: 10,
    borderWidth: 1,
    gap: 8,
  },
  datePickerText: { fontSize: 14, fontWeight: '500' },
  durationHint: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    marginTop: 4,
  },
  durationHintText: { fontSize: 12, fontWeight: '500' },
  chipScroll: { marginTop: 4 },
  chipOption: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    marginRight: 8,
    borderWidth: 1,
  },
  chipOptionText: { fontSize: 13, fontWeight: '500' },
  switchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 10,
    borderRadius: 10,
    borderWidth: 1,
  },
  switchLabel: { fontSize: 14 },

  // Deals Section
  dealsSection: { marginTop: 8, paddingTop: 16, borderTopWidth: 1 },
  dealsSectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  sectionTitle: { fontSize: 15, fontWeight: '600' },
  addDealBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 8,
    gap: 4,
  },
  addDealBtnText: { color: Colors.light.card, fontWeight: '600', fontSize: 13 },
  dealItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    borderRadius: 10,
    marginBottom: 8,
    borderWidth: 1,
  },
  dealItemImage: { width: 50, height: 50, borderRadius: 8, marginRight: 12 },
  dealItemImagePlaceholder: {
    width: 50,
    height: 50,
    borderRadius: 8,
    marginRight: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  dealItemInfo: { flex: 1 },
  dealItemStore: { fontSize: 14, fontWeight: '600', marginBottom: 4 },
  dealItemBenefits: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  dealItemBenefit: {
    fontSize: 10,
    color: Colors.light.secondaryText,
    backgroundColor: Colors.light.background,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  dealEndsIn: { fontSize: 10, marginTop: 4 },
  dealItemActions: { flexDirection: 'column', gap: 6 },
  dealActionBtn: { padding: 8, borderRadius: 6 },
  removeDealBtn: { padding: 4 },

  // Offer Details Section
  offerDetailsSection: {
    marginBottom: 16,
    padding: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderStyle: 'dashed',
  },
  offerDetailsTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 14 },
  offerDetailsTitle: { fontSize: 15, fontWeight: '600' },
  multilineInput: { height: 100, textAlignVertical: 'top', paddingTop: 10 },

  // Images Section
  imagesSection: {
    marginBottom: 16,
    padding: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderStyle: 'dashed',
  },
  imagesSectionHeader: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 14 },
  imagesSectionTitle: { fontSize: 15, fontWeight: '600' },
  labelWithUpload: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  uploadBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 6,
    gap: 4,
  },
  uploadBtnText: { color: Colors.light.card, fontSize: 12, fontWeight: '600' },
  imagePlaceholder: {
    height: 140,
    borderRadius: 10,
    borderWidth: 2,
    borderStyle: 'dashed',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
  },
  imagePlaceholderText: { fontSize: 12, textAlign: 'center' },
  campaignImagePreview: {
    marginBottom: 10,
    borderRadius: 10,
    overflow: 'hidden',
    position: 'relative',
  },
  bannerPreview: { width: '100%', height: 120, borderRadius: 10 },
  iconPreview: { width: 60, height: 60, borderRadius: 10 },
  removeImageBtn: {
    position: 'absolute',
    top: 8,
    right: 8,
    backgroundColor: Colors.light.card,
    borderRadius: 12,
  },

  // Deal Modal
  dealModalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center' },
  dealModalScrollContent: { flexGrow: 1, justifyContent: 'center', padding: 20 },
  dealModalContent: { borderRadius: 16, padding: 20 },
  imagePreviewContainer: {
    marginBottom: 12,
    borderRadius: 10,
    overflow: 'hidden',
    position: 'relative',
  },
  imagePreview: { width: '100%', height: 140, borderRadius: 10 },
  dealModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  dealModalTitle: { fontSize: 18, fontWeight: '600' },
  dealModalButtons: { flexDirection: 'row', marginTop: 8, gap: 12 },
  dealModalBtn: { flex: 1, paddingVertical: 12, borderRadius: 10, alignItems: 'center' },
  dealModalCancelBtn: { borderWidth: 1 },
  dealModalSaveBtn: {},
  dealModalBtnText: { fontWeight: '600', fontSize: 14 },
  dealTypeBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    borderWidth: 1.5,
  },
  currencyBtn: {
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 6,
    borderWidth: 1,
    minWidth: 40,
  },

  // Web Date Picker styles
  webInlineDatePicker: {
    marginBottom: 16,
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  webDatePickerHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 12, gap: 8 },
  webDatePickerHeaderText: { flex: 1, fontSize: 15, fontWeight: '600' },
  webDatePickerClose: { padding: 4 },

  // Store Selection Styles
  storeSelectBtn: { borderRadius: 10, borderWidth: 1, padding: 12 },
  selectedStoreInfo: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  selectedStoreName: { flex: 1, fontSize: 14, fontWeight: '500' },
  clearStoreBtn: { padding: 2 },
  selectStorePlaceholder: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  selectStorePlaceholderText: { fontSize: 14 },
  linkedStoreHint: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 6,
  },
  linkedStoreHintText: { fontSize: 11, fontWeight: '500' },

  // Store Selector Modal
  storeSelectorOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    padding: 20,
  },
  storeSelectorContent: { borderRadius: 16, maxHeight: '80%', overflow: 'hidden' },
  storeSelectorHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: Colors.light.border,
  },
  storeSelectorTitle: { fontSize: 18, fontWeight: '600' },
  storeSearchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 16,
    marginVertical: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1,
    gap: 8,
  },
  storeSearchInput: { flex: 1, fontSize: 14, padding: 0 },
  storeList: { paddingHorizontal: 16, paddingBottom: 16, maxHeight: 400 },
  storesLoadingContainer: { paddingVertical: 40, alignItems: 'center' },
  noStoresContainer: { paddingVertical: 40, alignItems: 'center', gap: 8 },
  noStoresText: { fontSize: 14 },
  storeListItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    borderRadius: 10,
    borderWidth: 1,
    marginBottom: 8,
    gap: 12,
  },
  storeListItemImage: { width: 44, height: 44, borderRadius: 8 },
  storeListItemImagePlaceholder: {
    width: 44,
    height: 44,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  storeListItemInfo: { flex: 1 },
  storeListItemName: { fontSize: 14, fontWeight: '600', marginBottom: 2 },
  storeListItemCategory: { fontSize: 12 },

  // Deal linked store status
  dealLinkedStore: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 4 },
  dealLinkedStoreText: { fontSize: 9, color: Colors.light.success, fontWeight: '500' },
  dealUnlinkedStore: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 4 },
  dealUnlinkedStoreText: { fontSize: 9, color: Colors.light.warning, fontWeight: '500' },
});
