import { StyleSheet } from 'react-native';
import { Colors } from '@/constants/Colors';

export const s = StyleSheet.create({
  container: { flex: 1 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
  },
  headerLeft: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  headerTitle: { fontSize: 18, fontWeight: '700' },
  headerActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  iconBtn: { padding: 8 },
  saveButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: Colors.light.navy,
  },
  saveButtonDisabled: { backgroundColor: Colors.light.muted },
  saveButtonText: { fontWeight: '600', color: Colors.light.card, fontSize: 14 },
  scrollContent: { padding: 16, paddingBottom: 60 },
  card: { borderRadius: 12, marginBottom: 12, borderWidth: 1, overflow: 'hidden' },
  cardHeader: { flexDirection: 'row', alignItems: 'center', padding: 16, gap: 8 },
  cardTitle: { flex: 1, fontSize: 16, fontWeight: '700' },
  cardBody: { paddingHorizontal: 16, paddingBottom: 16, borderTopWidth: 1 },
  badge: { paddingHorizontal: 8, paddingVertical: 2, borderRadius: 10 },
  badgeText: { fontSize: 12, fontWeight: '700' },
  sectionDescription: { fontSize: 13, marginTop: 8, marginBottom: 12, lineHeight: 18 },
  fieldRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 12,
  },
  fieldLabel: { fontSize: 13, fontWeight: '600', flex: 1 },
  fieldInput: {
    borderRadius: 8,
    padding: 10,
    borderWidth: 1,
    minWidth: 120,
    textAlign: 'right',
    fontSize: 14,
  },
  categoryRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 8,
    paddingBottom: 12,
    marginTop: 12,
    borderBottomWidth: 1,
  },
  listItemLabel: { fontSize: 11, fontWeight: '600', marginBottom: 4 },
  listInput: {
    fontSize: 14,
    borderWidth: 1,
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  multiplierContainer: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  multiplierSuffix: { fontSize: 14, fontWeight: '700' },
  removeBtn: { padding: 8, justifyContent: 'center' },
  addBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderRadius: 8,
    marginTop: 12,
  },
  addBtnText: { fontSize: 13, fontWeight: '600' },
  emptyText: { fontSize: 13, textAlign: 'center', paddingVertical: 16, fontStyle: 'italic' },
  campaignLoadingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 20,
  },
  campaignLoadingText: { fontSize: 13 },
  campaignErrorContainer: { alignItems: 'center', paddingVertical: 16, gap: 8 },
  campaignErrorText: { fontSize: 13, textAlign: 'center' },
  retryBtn: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    marginTop: 4,
  },
  retryBtnText: { fontSize: 13, fontWeight: '600' },
  campaignCard: { borderWidth: 1, borderRadius: 10, padding: 12, marginTop: 10 },
  campaignHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  campaignName: { fontSize: 14, fontWeight: '700', flex: 1 },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 10,
  },
  statusDot: { width: 6, height: 6, borderRadius: 3 },
  statusText: { fontSize: 11, fontWeight: '700' },
  campaignDetails: { marginTop: 8, gap: 4 },
  campaignDetail: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  campaignDetailText: { fontSize: 12 },
  configLoadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 60,
    gap: 12,
  },
  configLoadingText: { fontSize: 14 },
  bottomSave: {
    backgroundColor: Colors.light.navy,
    borderRadius: 10,
    padding: 14,
    alignItems: 'center',
    marginTop: 8,
  },
  bottomSaveText: { color: Colors.light.card, fontSize: 16, fontWeight: '700' },
});
