import { StyleSheet } from 'react-native';
import { Colors } from '@/constants/Colors';

export const s = StyleSheet.create({
  container: { flex: 1 },
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  headerTitle: { fontSize: 24, fontWeight: '700' },
  headerSubtitle: { fontSize: 13, marginTop: 2 },
  statsRow: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    gap: 6,
    marginBottom: 12,
    flexWrap: 'wrap',
  },
  statItem: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderRadius: 12,
    alignItems: 'center',
  },
  statValue: { fontSize: 17, fontWeight: '700' },
  statLabel: { fontSize: 10, fontWeight: '500', marginTop: 2 },
  funnelContainer: { marginHorizontal: 16, marginBottom: 12, padding: 14, borderRadius: 10 },
  funnelTitle: { fontSize: 13, fontWeight: '700', marginBottom: 10 },
  funnelStep: { marginBottom: 8 },
  funnelLabelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  funnelStepLabel: { fontSize: 12, fontWeight: '600' },
  funnelStepCount: { fontSize: 11 },
  funnelBarBg: { height: 8, borderRadius: 4, overflow: 'hidden' },
  funnelBar: { height: '100%', borderRadius: 4 },
  filterRow: { paddingHorizontal: 16, gap: 6, flexDirection: 'row', alignItems: 'center' },
  filterChip: { paddingHorizontal: 12, paddingVertical: 7, borderRadius: 20, borderWidth: 1 },
  filterChipText: { fontSize: 12, fontWeight: '600' },
  filterDivider: {
    width: 1,
    height: 20,
    backgroundColor: Colors.light.gray200,
    marginHorizontal: 4,
  },
  buttonRow: { flexDirection: 'row', paddingHorizontal: 16, gap: 8, marginBottom: 12 },
  createBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    borderRadius: 10,
    gap: 6,
  },
  templateBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    borderRadius: 10,
    gap: 6,
  },
  createBtnText: { color: Colors.light.card, fontWeight: '600', fontSize: 14 },
  listContent: { paddingHorizontal: 16, paddingBottom: 16 },
  emptyContainer: { paddingVertical: 60, alignItems: 'center' },
  emptyTitle: { fontSize: 18, fontWeight: '600', marginTop: 12 },
  emptyText: { fontSize: 14, marginTop: 4 },
});
