import { StyleSheet } from 'react-native';
import { Colors } from '@/constants/Colors';

export const styles = StyleSheet.create({
  container: { flex: 1 },
  background: { flex: 1 },
  center: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  header: { paddingHorizontal: 16, paddingVertical: 12 },
  headerTitle: { fontSize: 20, fontWeight: '700' },
  card: { borderRadius: 12, padding: 16, marginHorizontal: 16, marginBottom: 12 },
  cell: { padding: 8 },
  cohortCell: { padding: 8, alignItems: 'center', justifyContent: 'center' },
  headerCell: { padding: 8, alignItems: 'center' },
  emptyContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', paddingTop: 60 },
  emptyMessage: { fontSize: 16, fontWeight: '600', marginTop: 8 },
  emptyTitle: { fontSize: 14 },
  filter: { paddingHorizontal: 16, marginBottom: 12 },
  infoCard: {
    backgroundColor: Colors.light.card,
    borderRadius: 12,
    padding: 16,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: Colors.light.gray200,
  },
  infoTitle: { fontSize: 15, fontWeight: '700', marginBottom: 4 },
  infoSub: { fontSize: 12, color: Colors.light.secondaryText },
  tableScroll: { flex: 1, overflow: 'hidden' },
  table: { borderWidth: 1, borderColor: Colors.light.gray200, borderRadius: 8 },
  tableRow: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: Colors.light.gray200 },
  usersCell: { padding: 8, minWidth: 80, alignItems: 'center', justifyContent: 'center' },
  retentionCell: { padding: 8, minWidth: 60, alignItems: 'center', justifyContent: 'center' },
  retentionText: { fontSize: 13, fontWeight: '600' },
  retentionEmpty: { fontSize: 12, color: Colors.light.secondaryText },
  insightRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 12,
  },
  insightCard: {
    flex: 1,
    minWidth: '45%',
    backgroundColor: Colors.light.card,
    borderRadius: 12,
    padding: 14,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Colors.light.gray200,
  },
  insightValue: { fontSize: 22, fontWeight: '700', marginBottom: 4 },
  insightLabel: { fontSize: 11, color: Colors.light.secondaryText, textAlign: 'center' },
});
export const s = styles;
