import { StyleSheet } from 'react-native';
import { Colors } from '@/constants/Colors';

export const s = StyleSheet.create({
  container: { flex: 1 },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
  },
  headerTitle: { fontSize: 22, fontWeight: '700' },
  headerSubtitle: { fontSize: 13, fontWeight: '500' },
  searchBar: { paddingHorizontal: 16, paddingVertical: 10 },
  searchInput: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    gap: 8,
  },
  searchTextInput: { flex: 1, fontSize: 14, paddingVertical: 0 },
  filtersBar: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: Colors.light.gray200,
  },
  filterRow: { flexDirection: 'row' },
  filterChip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    backgroundColor: Colors.light.backgroundSecondary,
    marginRight: 8,
  },
  filterChipActive: { backgroundColor: Colors.light.info },
  chipText: { fontSize: 12, color: Colors.light.mutedDark, fontWeight: '500' },
  chipTextActive: { color: Colors.light.card, fontWeight: '600' },
  card: {
    borderRadius: 12,
    marginBottom: 10,
    borderWidth: 1,
    padding: 14,
  },
  cardTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  cardLeftCol: { flex: 1, marginRight: 12, gap: 4 },
  cardRightCol: { alignItems: 'flex-end', gap: 4 },
  userRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  userLabel: { fontSize: 11, fontWeight: '500' },
  userName: { fontSize: 13, fontWeight: '600', flexShrink: 1 },
  amount: { fontSize: 18, fontWeight: '700' },
  coinBadge: { paddingHorizontal: 8, paddingVertical: 2, borderRadius: 8 },
  coinBadgeText: { fontSize: 10, fontWeight: '600', textTransform: 'uppercase' },
  cardBottomRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderTopWidth: 1,
    borderTopColor: Colors.light.backgroundSecondary,
    paddingTop: 10,
  },
  statusBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 8 },
  statusText: { fontSize: 11, fontWeight: '600', textTransform: 'capitalize' },
  deliveryBadge: { flexDirection: 'row', alignItems: 'center', gap: 3 },
  deliveryText: { fontSize: 11, color: Colors.light.mutedDark, fontWeight: '500' },
  dateText: { fontSize: 11, color: Colors.light.muted, marginLeft: 'auto' },
  emptyBox: { paddingVertical: 40, alignItems: 'center' },
  emptyText: { fontSize: 14, color: Colors.light.muted, marginTop: 10 },
  // Detail Modal
  modalContainer: { flex: 1 },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderBottomWidth: 1,
  },
  modalTitle: { fontSize: 17, fontWeight: '600' },
  detailScroll: { paddingHorizontal: 20 },
  detailSection: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: Colors.light.backgroundSecondary,
  },
  sectionTitle: { fontSize: 13, fontWeight: '600', color: Colors.light.mutedDark, marginBottom: 6 },
  detailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 4,
  },
  detailLabel: { fontSize: 13, fontWeight: '500', color: Colors.light.mutedDark },
  detailValue: { fontSize: 14, fontWeight: '600' },
  phoneText: { fontSize: 12, color: Colors.light.muted, marginTop: 2 },
  messageText: {
    fontSize: 14,
    lineHeight: 20,
    backgroundColor: Colors.light.backgroundTertiary,
    padding: 10,
    borderRadius: 8,
    overflow: 'hidden',
  },
  txRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 6,
    borderBottomWidth: 1,
  },
  txType: { fontSize: 13, fontWeight: '500' },
  txAmount: { fontSize: 13, fontWeight: '600' },
  detailActions: {
    flexDirection: 'row',
    gap: 12,
    paddingVertical: 20,
  },
  actionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    borderRadius: 10,
    gap: 6,
  },
  refundButton: { backgroundColor: Colors.light.errorDark },
  deliverButton: { backgroundColor: '#2563EB' },
  actionButtonText: { color: Colors.light.card, fontSize: 14, fontWeight: '600' },
  // Refund modal styles
  refundModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  refundModalCard: {
    width: '100%',
    maxWidth: 420,
    borderRadius: 14,
    padding: 20,
    gap: 12,
  },
  refundModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  refundModalTitle: { fontSize: 17, fontWeight: '700' },
  refundModalSubtitle: { fontSize: 13, marginTop: -4 },
  refundFieldLabel: { fontSize: 13, fontWeight: '600' },
  refundInput: {
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 9,
    fontSize: 14,
    minHeight: 80,
    textAlignVertical: 'top',
  },
  refundModalActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 4,
  },
  refundCancelBtn: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    borderRadius: 8,
    borderWidth: 1,
    minHeight: 44,
  },
  refundConfirmBtn: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    borderRadius: 8,
    minHeight: 44,
  },
  refundBtnText: { fontSize: 14, fontWeight: '600' },
});
