import { StyleSheet } from 'react-native';
import { Colors } from '@/constants/Colors';

export const styles = StyleSheet.create({
  container: { flex: 1 },
  header: { padding: 16 },
  headerTitle: { fontSize: 20, fontWeight: '700' },
  headerSubtitle: { fontSize: 13, marginTop: 2 },
  pageTitle: { fontSize: 18, fontWeight: '700' },
  content: { flex: 1, padding: 16 },
  statsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginBottom: 16 },
  statCard: {
    flex: 1,
    minWidth: '30%',
    padding: 12,
    borderRadius: 10,
    borderLeftWidth: 3,
    borderLeftColor: Colors.light.border,
    backgroundColor: Colors.light.card,
    alignItems: 'center',
  },
  statValue: { fontSize: 20, fontWeight: '700', marginBottom: 2 },
  statLabel: { fontSize: 11, fontWeight: '500', color: Colors.light.secondaryText },
  avgResolutionHours: { fontSize: 18, fontWeight: '700', marginBottom: 2 },
  refundRate: { fontSize: 18, fontWeight: '700', marginBottom: 2 },
  resolvedToday: { fontSize: 18, fontWeight: '700', marginBottom: 2 },
  open: { fontSize: 18, fontWeight: '700', marginBottom: 2, color: Colors.light.error },
  underReview: { fontSize: 18, fontWeight: '700', marginBottom: 2, color: Colors.light.warning },
  escalated: { fontSize: 18, fontWeight: '700', marginBottom: 2, color: Colors.light.purple },
  filterSection: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: Colors.light.gray200,
  },
  searchRow: { flexDirection: 'row', gap: 8, alignItems: 'center' },
  search: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 8 },
  searchInput: {
    flex: 1,
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    fontSize: 13,
  },
  searchBtn: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: Colors.light.info,
  },
  filterBar: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: Colors.light.gray200,
    gap: 8,
  },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  chip: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Colors.light.gray200,
  },
  chipActive: { backgroundColor: Colors.light.info, borderColor: Colors.light.info },
  chipText: { fontSize: 12, fontWeight: '500' },
  chipTextActive: { fontSize: 12, fontWeight: '600', color: Colors.light.card },
  decisionChip: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.light.gray200,
  },
  decisionChipActive: { backgroundColor: Colors.light.success, borderColor: Colors.light.success },
  decisionChipText: { fontSize: 11, fontWeight: '500' },
  decisionChipTextActive: { fontSize: 11, fontWeight: '600', color: Colors.light.card },
  filterChip: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Colors.light.gray200,
  },
  filterChipActive: { backgroundColor: Colors.light.info, borderColor: Colors.light.info },
  filterChipText: { fontSize: 12, fontWeight: '500' },
  listContent: { padding: 16, paddingBottom: 60 },
  card: {
    borderRadius: 12,
    padding: 14,
    marginBottom: 10,
    backgroundColor: Colors.light.card,
    borderWidth: 1,
    borderColor: Colors.light.gray200,
  },
  cardBody: { flex: 1 },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  cardId: { fontSize: 11, color: Colors.light.secondaryText },
  cardTitle: { fontSize: 14, fontWeight: '600', marginTop: 2 },
  cardMeta: { fontSize: 12, color: Colors.light.secondaryText, marginTop: 4 },
  cardRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  cardRowText: { fontSize: 12, color: Colors.light.secondaryText },
  cardFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: Colors.light.gray200,
  },
  disputeNumber: { fontSize: 11, color: Colors.light.secondaryText, fontFamily: 'monospace' },
  priorityBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 4, marginLeft: 8 },
  priorityBadgeText: { fontSize: 10, fontWeight: '700', textTransform: 'uppercase' },
  priorityDot: { width: 8, height: 8, borderRadius: 4, marginRight: 6 },
  priority: { fontSize: 11, fontWeight: '600' },
  statusBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 6 },
  statusBadgeText: { fontSize: 11, fontWeight: '600' },
  status: { fontSize: 12, fontWeight: '600' },
  badge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 4 },
  badgeText: { fontSize: 10, fontWeight: '700', textTransform: 'uppercase' },
  cardActions: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: Colors.light.gray200,
  },
  actionBtn: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: 8,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Colors.light.gray200,
  },
  actionBtnPrimary: { backgroundColor: Colors.light.info, borderColor: Colors.light.info },
  actionBtnText: { fontSize: 12, fontWeight: '600' },
  actionSection: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: Colors.light.gray200,
  },
  resolveActions: { flexDirection: 'row', gap: 8, marginTop: 8 },
  confirmBtn: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: 'center',
    backgroundColor: Colors.light.success,
  },
  confirmBtnText: { fontSize: 13, fontWeight: '600', color: Colors.light.card },
  cancelBtn: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Colors.light.gray200,
  },
  cancelBtnText: { fontSize: 13, fontWeight: '600' },
  resolveModal: { flex: 1, backgroundColor: Colors.light.card, borderRadius: 16, margin: 20 },
  resolveTitle: { fontSize: 17, fontWeight: '700', marginBottom: 16 },
  infoSection: { marginBottom: 16 },
  infoRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8 },
  infoLabel: { fontSize: 12, color: Colors.light.secondaryText },
  infoValue: { fontSize: 13, fontWeight: '500' },
  evidenceItem: {
    flexDirection: 'row',
    gap: 10,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: Colors.light.gray200,
  },
  evidenceType: {
    fontSize: 11,
    color: Colors.light.secondaryText,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  evidenceDesc: { fontSize: 13, marginTop: 4 },
  attachmentCount: { fontSize: 12, color: Colors.light.secondaryText },
  amountText: { fontSize: 14, fontWeight: '700' },
  dateText: { fontSize: 12, color: Colors.light.secondaryText },
  descText: { fontSize: 13, color: Colors.light.gray700 },
  detailRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 4 },
  decisionRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 12 },
  timelineAction: { marginTop: 8 },
  timelineDetails: { fontSize: 12, color: Colors.light.secondaryText, marginTop: 2 },
  emptyContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', paddingVertical: 60 },
  emptyState: { alignItems: 'center' },
  emptyTitle: { fontSize: 16, fontWeight: '600', marginTop: 12 },
  emptySubtitle: { fontSize: 13, color: Colors.light.secondaryText, marginTop: 4 },
  emptyText: { fontSize: 14, color: Colors.light.muted, marginTop: 8 },
  error: { fontSize: 12, color: Colors.light.error, marginTop: 4 },
  modalContainer: { flex: 1 },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: Colors.light.gray200,
  },
  modalTitle: { fontSize: 18, fontWeight: '700' },
  modalClose: { padding: 4 },
  modalBody: { padding: 16, flex: 1 },
  overlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center' },
  section: { marginBottom: 16 },
  sectionTitle: { fontSize: 15, fontWeight: '700', marginBottom: 8 },
  input: {
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: 14,
  },
  inputLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: Colors.light.secondaryText,
    marginBottom: 4,
  },
  pagination: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
  },
  pageBtn: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: Colors.light.info,
  },
  pageBtnDisabled: { opacity: 0.4 },
  pageBtnText: { color: Colors.light.card, fontWeight: '500', fontSize: 13 },
  pageInfo: { fontSize: 13, color: Colors.light.secondaryText },
  timelineItem: { flexDirection: 'row', marginBottom: 12, gap: 10 },
  timelineDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginTop: 5,
    backgroundColor: Colors.light.info,
  },
  timelineContent: { flex: 1 },
  timelineTime: { fontSize: 10, color: Colors.light.secondaryText },
  timelineText: { fontSize: 13, marginTop: 2 },
});
export const s = styles;
