import { StyleSheet } from 'react-native';
import { Colors } from '@/constants/Colors';

const styles = StyleSheet.create({
  container: { flex: 1 },
  listContent: { paddingBottom: 20 },

  // Header
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 12,
  },
  headerTitle: { fontSize: 24, fontWeight: '700' },
  headerSubtitle: { fontSize: 13, marginTop: 2 },
  createBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 10,
    gap: 6,
  },
  createBtnText: { color: Colors.light.card, fontWeight: '600', fontSize: 14 },

  // Stats
  statsRow: { flexDirection: 'row', paddingHorizontal: 16, gap: 8, marginBottom: 12 },
  statItem: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 12,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 1,
  },
  statValue: { fontSize: 20, fontWeight: '700' },
  statLabel: { fontSize: 11, marginTop: 2 },

  // Tabs
  tabsWrapper: { marginBottom: 8 },
  tabsContent: { paddingHorizontal: 16, gap: 8 },
  tabItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    gap: 6,
  },
  tabLabel: { fontSize: 13, fontWeight: '500' },

  // Search & Filter
  searchFilterContainer: { paddingHorizontal: 16, marginBottom: 12, gap: 10 },
  searchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 10,
    gap: 8,
  },
  searchInput: { flex: 1, fontSize: 14, padding: 0 },
  filterChipsRow: { gap: 8, paddingVertical: 2 },
  filterChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    borderWidth: 1,
    gap: 4,
  },
  filterChipText: { fontSize: 12, fontWeight: '500' },

  // Cards
  card: {
    marginHorizontal: 16,
    marginBottom: 12,
    borderRadius: 14,
    padding: 14,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
  },
  cardImageRow: { flexDirection: 'row', marginBottom: 10, gap: 10 },
  cardImage: { width: 80, height: 60, borderRadius: 8 },
  cardImagePlaceholder: {
    width: 80,
    height: 60,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardBadgesCol: { flex: 1, gap: 6, alignItems: 'flex-start' },
  statusChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    gap: 4,
  },
  statusLabel: { fontSize: 11, fontWeight: '600' },
  featuredChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    gap: 4,
  },
  featuredLabel: { fontSize: 11, fontWeight: '600' },
  cardTitle: { fontSize: 16, fontWeight: '600', marginBottom: 2 },
  cardCategory: { fontSize: 12, fontWeight: '500', marginBottom: 8 },
  metaRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginBottom: 10 },
  metaChip: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  metaText: { fontSize: 12 },
  bookingRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 8,
    marginBottom: 8,
    borderTopWidth: 1,
  },
  bookingInfo: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  bookingText: { fontSize: 12 },
  slotsText: { fontSize: 12 },
  actionRow: { flexDirection: 'row', gap: 8, paddingTop: 8 },
  actionIconBtn: {
    width: 36,
    height: 36,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },

  // Empty
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 60,
    paddingHorizontal: 40,
    gap: 12,
  },
  emptyTitle: { fontSize: 18, fontWeight: '600' },
  emptyText: { fontSize: 14, textAlign: 'center' },
  emptyBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 10,
    gap: 6,
    marginTop: 8,
  },
  emptyBtnText: { color: Colors.light.card, fontWeight: '600' },

  // Loading
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 60,
    gap: 12,
  },
  loadingText: { fontSize: 14 },

  // Modal
  modalContainer: { flex: 1 },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
  },
  modalCloseBtn: { padding: 4 },
  modalTitle: { fontSize: 18, fontWeight: '600' },
  modalSaveBtn: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
    minWidth: 60,
    alignItems: 'center',
  },
  modalSaveBtnText: { color: Colors.light.card, fontWeight: '600', fontSize: 14 },
  modalBody: { flex: 1 },
  modalBodyContent: { padding: 16 },

  // Form
  formGroup: { marginBottom: 14 },
  formLabel: { fontSize: 13, fontWeight: '600', marginBottom: 6 },
  formInput: {
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 14,
  },
  multilineInput: { height: 100, textAlignVertical: 'top', paddingTop: 12 },
  formRow: { flexDirection: 'row', alignItems: 'flex-start' },
  formSection: {
    marginBottom: 16,
    padding: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderStyle: 'dashed',
  },
  formSectionHeader: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 14 },
  formSectionTitle: { fontSize: 15, fontWeight: '600' },
  chipScroll: { marginBottom: 4 },
  chipOption: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    marginRight: 8,
  },
  chipOptionText: { fontSize: 13, fontWeight: '500' },
  switchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  switchLabel: { fontSize: 14 },
  imagePreview: { marginTop: 10, borderRadius: 10, overflow: 'hidden', position: 'relative' },
  previewImage: { width: '100%', height: 120, borderRadius: 10 },
  removeImageBtn: {
    position: 'absolute',
    top: 8,
    right: 8,
    backgroundColor: Colors.light.card,
    borderRadius: 12,
  },

  // Bookings
  bookingCard: { borderRadius: 12, padding: 14, marginBottom: 10, borderWidth: 1 },
  bookingCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 10,
  },
  bookingUserName: { fontSize: 15, fontWeight: '600' },
  bookingUserPhone: { fontSize: 12, marginTop: 2 },
  bookingStatusChip: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8 },
  bookingStatusText: { fontSize: 10, fontWeight: '700' },
  bookingCardMeta: { flexDirection: 'row', gap: 16, paddingTop: 10, borderTopWidth: 1 },
  bookingMetaItem: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  bookingMetaText: { fontSize: 12 },
  bookingRef: { fontSize: 11, marginTop: 8 },

  // Analytics
  analyticsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginBottom: 16 },
  analyticsCard: {
    width: '48%',
    padding: 14,
    borderRadius: 12,
    alignItems: 'center',
    gap: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 1,
  },
  analyticsValue: { fontSize: 20, fontWeight: '700' },
  analyticsLabel: { fontSize: 11, textAlign: 'center' },
  analyticsSection: { borderRadius: 12, padding: 14, marginBottom: 16 },
  analyticsSectionTitle: { fontSize: 15, fontWeight: '600', marginBottom: 12 },
  dayRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    borderBottomWidth: StyleSheet.hairlineWidth,
    gap: 10,
  },
  dayDate: { fontSize: 12, width: 80 },
  dayBarContainer: {
    flex: 1,
    height: 8,
    backgroundColor: Colors.light.backgroundSecondary,
    borderRadius: 4,
    overflow: 'hidden',
  },
  dayBar: { height: '100%', borderRadius: 4 },
  dayCount: { fontSize: 12, fontWeight: '600', width: 30, textAlign: 'right' },
});

export const s = styles;
export default styles;
