import { StyleSheet } from 'react-native';
import { Colors } from '@/constants/Colors';

export const styles = StyleSheet.create({
  container: { flex: 1 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  headerTitle: { fontSize: 20, fontWeight: '700' },
  headerSubtitle: { fontSize: 13, marginTop: 2 },
  backBtn: { padding: 4 },
  addBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 8,
    gap: 4,
  },
  addBtnText: { fontSize: 14, fontWeight: '600' },
  card: { borderRadius: 12, padding: 16, marginHorizontal: 16, marginBottom: 12 },
  cardTopRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  cardQuestion: { fontSize: 15, fontWeight: '600', flex: 1 },
  catBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 8 },
  catBadgeText: { fontSize: 11, fontWeight: '600' },
  cardBody: { marginTop: 8 },
  cardBottomRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 8,
  },
  cardActions: { flexDirection: 'row', gap: 8 },
  actionBtn: { paddingHorizontal: 10, paddingVertical: 5, borderRadius: 6 },
  actionText: { fontSize: 12, fontWeight: '600' },
  activeFilterRow: { flexDirection: 'row', paddingHorizontal: 16, marginBottom: 12, gap: 8 },
  activeChip: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 16 },
  activeChipSelected: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 16 },
  activeChipText: { fontSize: 13, fontWeight: '500' },
  activeChipTextSelected: { fontSize: 13, fontWeight: '600' },
  background: { flex: 1 },
  backgroundSecondary: { flex: 1 },
  border: { borderWidth: 1 },
  emptyState: { flex: 1, justifyContent: 'center', alignItems: 'center', paddingTop: 60 },
  emptyText: { fontSize: 16, fontWeight: '600', marginTop: 8 },
  colorStrip: { height: 4, borderRadius: 2 },
  statsRow: { flexDirection: 'row', gap: 8, marginBottom: 12 },
  statItem: { flex: 1, alignItems: 'center', padding: 12, borderRadius: 10 },
  statText: { fontSize: 20, fontWeight: '700', marginBottom: 2 },
  tagsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 8 },
  tagPill: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    backgroundColor: Colors.light.backgroundSecondary,
  },
  tagText: { fontSize: 11, fontWeight: '500', color: Colors.light.gray700 },
  moreText: { fontSize: 11, color: Colors.light.secondaryText },
  toggleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
  },
  switchRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
  },
  statusBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 8 },
  paginationBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
  },
  paginationInfo: { fontSize: 13, color: Colors.light.secondaryText },
  paginationButtons: { flexDirection: 'row', gap: 8 },
  pageBtn: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: Colors.light.gray200,
  },
  pageBtnDisabled: { opacity: 0.4 },
  pageBtnActive: { backgroundColor: Colors.light.info, borderColor: Colors.light.info },
  pageBtnText: { fontSize: 13, fontWeight: '500', color: Colors.light.text },
  pageBtnTextActive: { fontSize: 13, fontWeight: '600', color: Colors.light.card },
  activeBg: { backgroundColor: Colors.light.success },
  inactiveBg: { backgroundColor: Colors.light.gray200 },
  formInput: {
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 14,
  },
  multiline: { minHeight: 100, textAlignVertical: 'top' },
  modalContainer: { flex: 1, backgroundColor: Colors.light.backgroundSecondary },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: Colors.light.gray200,
  },
  modalTitle: { fontSize: 17, fontWeight: '700' },
  saveBtn: { fontSize: 16, fontWeight: '600', color: Colors.light.info },
  formScroll: { paddingHorizontal: 20 },
  formLabel: {
    fontSize: 13,
    fontWeight: '600',
    marginBottom: 4,
    color: Colors.light.secondaryText,
  },
  filterChip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Colors.light.gray200,
  },
  filterChipActive: { backgroundColor: Colors.light.info, borderColor: Colors.light.info },
  chipText: { fontSize: 12, fontWeight: '500', color: Colors.light.text },
  chipTextActive: { fontSize: 12, fontWeight: '600', color: Colors.light.card },
  createBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 8,
    gap: 4,
    backgroundColor: Colors.light.info,
  },
  createBtnText: { fontSize: 14, fontWeight: '600', color: Colors.light.card },
  searchBar: { paddingHorizontal: 16, paddingVertical: 10 },
  searchInput: {
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: 14,
  },
  searchTextInput: { flex: 1, fontSize: 14 },
  filtersBar: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: Colors.light.gray200,
  },
  filterRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  emptyBox: { alignItems: 'center', marginTop: 40 },
  emptySubtext: { fontSize: 14, color: Colors.light.secondaryText, marginTop: 4 },
});
export const s = styles;
