import { StyleSheet } from 'react-native';
import { Colors } from '@/constants/Colors';

export const gameConfigStyles = StyleSheet.create({
  container: { flex: 1 },
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  headerTitle: { fontSize: 24, fontWeight: '700' },
  headerSubtitle: { fontSize: 13, marginTop: 2 },
  seedBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 10,
    gap: 6,
  },
  seedBtnText: { color: Colors.light.card, fontWeight: '600', fontSize: 13 },
  statsRow: { flexDirection: 'row', paddingHorizontal: 16, gap: 8, marginBottom: 12 },
  statItem: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderRadius: 12,
    alignItems: 'center',
  },
  statValue: { fontSize: 20, fontWeight: '700' },
  statLabel: { fontSize: 10, fontWeight: '500', marginTop: 2 },
  listContent: { paddingHorizontal: 16, paddingBottom: 32 },
  card: { borderRadius: 14, padding: 14, marginBottom: 12 },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  cardTitleRow: { flexDirection: 'row', alignItems: 'center', flex: 1 },
  cardEmoji: { fontSize: 28 },
  cardTitle: { fontSize: 16, fontWeight: '700' },
  gameTypeBadge: {
    alignSelf: 'flex-start',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
    marginTop: 3,
  },
  gameTypeText: { fontSize: 11, fontWeight: '600' },
  featuredBtn: { padding: 4 },
  cardDescription: { fontSize: 13, marginBottom: 10, lineHeight: 18 },
  infoRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginBottom: 10 },
  infoChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    gap: 4,
  },
  infoChipText: { fontSize: 11, fontWeight: '500' },
  actionsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderTopWidth: 1,
    paddingTop: 10,
  },
  toggleRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  toggleLabel: { fontSize: 13, fontWeight: '500' },
  actionBtns: { flexDirection: 'row', gap: 8 },
  actionIconBtn: {
    width: 36,
    height: 36,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  emptyContainer: { paddingVertical: 60, alignItems: 'center' },
  emptyTitle: { fontSize: 18, fontWeight: '600', marginTop: 12 },
  emptyText: { fontSize: 14, marginTop: 4, textAlign: 'center', paddingHorizontal: 32 },
  createNewBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    borderWidth: 2,
    borderStyle: 'dashed',
    borderRadius: 14,
    gap: 8,
    marginTop: 4,
  },
  createNewBtnText: { fontSize: 14, fontWeight: '600' },
  modalContainer: { flex: 1 },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
  },
  modalCloseBtn: { padding: 4 },
  modalTitle: { fontSize: 17, fontWeight: '600', flex: 1, textAlign: 'center' },
  modalSaveBtn: { paddingHorizontal: 16, paddingVertical: 8, borderRadius: 8 },
  modalSaveBtnText: { color: Colors.light.card, fontWeight: '600', fontSize: 14 },
  formTabsScroll: { maxHeight: 48, borderBottomWidth: 0 },
  formTabsRow: { flexDirection: 'row', paddingHorizontal: 16, paddingVertical: 8, gap: 8 },
  formTab: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
    gap: 4,
  },
  formTabLabel: { fontSize: 12, fontWeight: '600' },
  formScroll: { flex: 1 },
  formContent: { padding: 16, paddingBottom: 40 },
  formGroup: { marginBottom: 16 },
  formLabel: { fontSize: 13, fontWeight: '600', marginBottom: 6 },
  formLabelSmall: { fontSize: 11, fontWeight: '600', marginBottom: 4 },
  formHint: { fontSize: 12, marginBottom: 8 },
  formInput: {
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 14,
  },
  formInputSmall: {
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 13,
  },
  textArea: { minHeight: 80, textAlignVertical: 'top' },
  jsonTextArea: { minHeight: 200, textAlignVertical: 'top', fontSize: 12, lineHeight: 18 },
  formRow: { flexDirection: 'row', marginBottom: 0 },
  difficultySection: { borderWidth: 1, borderRadius: 12, padding: 12, marginBottom: 12 },
  difficultyLabel: { fontSize: 14, fontWeight: '700', marginBottom: 8 },
  daysRow: { flexDirection: 'row', gap: 6, flexWrap: 'wrap' },
  dayChip: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 8, borderWidth: 1 },
  dayChipText: { fontSize: 13, fontWeight: '600' },
  schedulePreview: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    borderRadius: 8,
    gap: 8,
  },
  schedulePreviewText: { fontSize: 13, fontWeight: '500' },
  rewardPreview: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    borderRadius: 10,
    gap: 8,
  },
  rewardPreviewText: { fontSize: 14, fontWeight: '600', color: Colors.light.success },
  gameTypeGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  gameTypeOption: {
    width: '48%',
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    borderRadius: 10,
    borderWidth: 1.5,
    gap: 8,
  },
  gameTypeOptionEmoji: { fontSize: 22 },
  gameTypeOptionLabel: { fontSize: 13, fontWeight: '600', flex: 1 },
  pageTabsRow: { flexDirection: 'row', borderBottomWidth: 1, paddingHorizontal: 16 },
  pageTab: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 14,
    marginRight: 4,
    gap: 6,
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  pageTabLabel: { fontSize: 13, fontWeight: '600' },
  sectionTitle: { fontSize: 16, fontWeight: '700', marginBottom: 10, paddingHorizontal: 4 },
  banModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    padding: 20,
  },
  banModalContent: { borderRadius: 16, padding: 20 },
  banModalTitle: { fontSize: 18, fontWeight: '600', marginBottom: 4 },
  banModalSubtitle: { fontSize: 13, marginBottom: 16 },
  banReasonInput: {
    borderWidth: 1,
    borderRadius: 8,
    padding: 12,
    minHeight: 80,
    textAlignVertical: 'top',
  },
  banModalButtons: { flexDirection: 'row', marginTop: 16, gap: 12 },
  banModalButton: { flex: 1, paddingVertical: 12, borderRadius: 8, alignItems: 'center' },
  banModalButtonText: { fontWeight: '600' },
});
