import { Platform, StyleSheet } from 'react-native';
import { Colors } from '@/constants/Colors';

export const s = StyleSheet.create({
  root: { flex: 1 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: Platform.OS === 'ios' ? 56 : 16,
    paddingBottom: 12,
  },
  headerTitle: { fontSize: 22, fontWeight: '800' },
  tabBar: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: '#E2E8F0' },
  tab: { flex: 1, paddingVertical: 10, alignItems: 'center' },
  tabActive: { borderBottomWidth: 2, borderBottomColor: '#06B6D4' },
  tabText: { fontSize: 12, fontWeight: '600', color: '#64748B' },
  tabTextActive: { color: '#06B6D4' },
  content: { padding: 16 },
  sectionTitle: { fontSize: 15, fontWeight: '700', color: '#0F172A', marginBottom: 10 },
  statsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  statCard: {
    width: '47%',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 12,
    gap: 10,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOpacity: 0.05,
        shadowRadius: 4,
        shadowOffset: { width: 0, height: 1 },
      },
      android: { elevation: 1 },
    }),
  },
  statIconBox: {
    width: 36,
    height: 36,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  statLabel: { fontSize: 11, color: '#64748B', fontWeight: '600' },
  statValue: { fontSize: 16, fontWeight: '800' },
  statSub: { fontSize: 10, color: '#94A3B8' },
  liabilityCard: {
    backgroundColor: '#fff',
    borderRadius: 14,
    padding: 16,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOpacity: 0.06,
        shadowRadius: 6,
        shadowOffset: { width: 0, height: 2 },
      },
      android: { elevation: 2 },
    }),
  },
  liabilityHeading: { fontSize: 14, fontWeight: '700', color: '#0F172A', marginBottom: 12 },
  liabilityRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  liabilityLabel: { fontSize: 14, color: '#64748B' },
  liabilityValue: { fontSize: 15, fontWeight: '800' },
  brandCoinRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
  },
  brandCoinHotel: { flex: 1, fontSize: 13, fontWeight: '600', color: '#0F172A' },
  brandCoinName: { fontSize: 11, color: '#94A3B8', marginRight: 12 },
  brandCoinAmount: { fontSize: 13, fontWeight: '800' },
  hotelRow: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderRadius: 14,
    padding: 14,
    marginBottom: 10,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOpacity: 0.05,
        shadowRadius: 4,
        shadowOffset: { width: 0, height: 1 },
      },
      android: { elevation: 1 },
    }),
  },
  hotelName: { fontSize: 14, fontWeight: '700', color: '#0F172A' },
  hotelCity: { fontSize: 12, color: '#64748B', marginTop: 1 },
  hotelStat: { fontSize: 11, color: '#64748B' },
  statusDot: { width: 7, height: 7, borderRadius: 4 },
  onboardBadge: { borderRadius: 6, paddingHorizontal: 8, paddingVertical: 3 },
  onboardText: { fontSize: 10, fontWeight: '700', textTransform: 'capitalize' },
  coinBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    backgroundColor: '#F5F3FF',
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  coinBadgeText: { fontSize: 10, color: '#7C3AED', fontWeight: '600' },
  searchBox: {
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    padding: 12,
    fontSize: 14,
    color: '#0F172A',
    backgroundColor: '#fff',
    marginBottom: 12,
  },
  emptyText: { fontSize: 14, color: '#94A3B8', textAlign: 'center', marginTop: 20 },
  perHotelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 14,
    marginBottom: 8,
  },
  perHotelName: { fontSize: 14, fontWeight: '600', color: '#0F172A' },
  perHotelCity: { fontSize: 11, color: '#94A3B8', marginTop: 2 },
  perHotelAmount: { fontSize: 15, fontWeight: '800', color: '#7C3AED' },
});
