import { StyleSheet } from 'react-native';
import { Colors } from '@/constants/Colors';

export const s = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8F9FA' },
  center: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  summaryRow: { flexDirection: 'row', gap: 8, padding: 16 },
  summaryCard: {
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: 12,
    borderWidth: 2,
    padding: 10,
    alignItems: 'center',
  },
  summaryNum: { fontSize: 20, fontWeight: '800', color: '#1a3a52' },
  summaryLabel: { fontSize: 11, color: '#6B7280', marginTop: 2 },
  realtimeBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#EF4444',
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  realtimeBannerText: { color: '#fff', fontWeight: '600', flex: 1, fontSize: 13 },
  filterRow: { paddingHorizontal: 16, marginBottom: 8, maxHeight: 44 },
  filterChip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    backgroundColor: '#fff',
    marginRight: 8,
  },
  filterChipActive: { backgroundColor: '#1a3a52', borderColor: '#1a3a52' },
  filterChipText: { fontSize: 12, color: '#374151' },
  filterChipTextActive: { color: '#fff', fontWeight: '600' },
  list: { flex: 1, paddingHorizontal: 16 },
  jobCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 14,
    marginBottom: 8,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  jobCardFailing: { borderLeftWidth: 3, borderLeftColor: '#EF4444' },
  jobHeader: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  jobInfo: { flex: 1 },
  jobName: { fontSize: 14, fontWeight: '600', color: '#1a3a52' },
  jobMeta: { fontSize: 12, color: '#6B7280', marginTop: 2 },
  statusBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 8 },
  statusText: { fontSize: 11, fontWeight: '700' },
  jobDetail: { marginTop: 12, paddingTop: 12, borderTopWidth: 1, borderTopColor: '#F3F4F6' },
  detailRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 6 },
  detailLabel: { fontSize: 12, color: '#6B7280' },
  detailValue: { fontSize: 12, fontWeight: '600', color: '#1a3a52' },
  errorBox: { backgroundColor: '#FEF2F2', borderRadius: 8, padding: 10, marginTop: 8 },
  errorLabel: { fontSize: 11, fontWeight: '700', color: '#DC2626', marginBottom: 4 },
  errorText: { fontSize: 12, color: '#7F1D1D' },
  runBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 10,
    backgroundColor: '#EEF2F7',
    borderRadius: 8,
    padding: 8,
    alignSelf: 'flex-start',
  },
  runBtnDisabled: { opacity: 0.6 },
  runBtnText: { fontSize: 13, color: '#1a3a52', fontWeight: '600' },
});
