import { StyleSheet } from 'react-native';
import { Colors } from '@/constants/Colors';

export const s = StyleSheet.create({
  safeArea: { flex: 1 },
  loadingOuter: {
    flex: 1,
    backgroundColor: Colors.light.background,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingInner: { alignItems: 'center', gap: 12 },
  loadingText: { color: Colors.light.navy, fontSize: 14, fontWeight: '500' },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: Colors.light.navy,
    gap: 8,
  },
  backBtn: { padding: 4 },
  topBarCenter: { flex: 1 },
  topBarTitle: { color: '#fff', fontSize: 16, fontWeight: '800', letterSpacing: 1 },
  topBarSub: { color: 'rgba(255,255,255,0.65)', fontSize: 11, marginTop: 1 },
  topBarRight: { flexDirection: 'row', alignItems: 'center' },
  statusPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(255,255,255,0.1)',
    paddingHorizontal: 7,
    paddingVertical: 4,
    borderRadius: 20,
  },
  statusPillText: { fontSize: 10, fontWeight: '700' },
  healthBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 8,
    gap: 7,
  },
  healthBannerText: { fontSize: 12, fontWeight: '500', flex: 1 },
  scroll: { flex: 1 },
  scrollContent: { paddingBottom: 40 },
  card: {
    marginHorizontal: 16,
    marginTop: 12,
    backgroundColor: Colors.light.card,
    borderRadius: 14,
    padding: 14,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  cardHeaderLeft: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  cardIconBox: {
    width: 30,
    height: 30,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardTitle: { fontSize: 14, fontWeight: '700', color: Colors.light.text },
  tableHead: { flexDirection: 'row', paddingBottom: 7, borderBottomWidth: 1, marginBottom: 2 },
  tableHeadCell: {
    fontSize: 10,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    color: Colors.light.muted,
  },
  tableRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 8 },
  tableCell: { fontSize: 12, color: Colors.light.text },
  footer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 24,
    paddingBottom: 32,
  },
  footerText: { fontSize: 11, color: Colors.light.muted, fontWeight: '500' },
});
