import { StyleSheet } from 'react-native';
import { Colors } from '@/constants/Colors';

export const s = StyleSheet.create({
  container: { flex: 1 },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  loadingText: { marginTop: 12, fontSize: 14 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
  },
  title: { fontSize: 20, fontWeight: '700' },
  headerRight: { flexDirection: 'row', alignItems: 'center' },
  liveBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: '#dcfce7',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
  },
  liveDot: { width: 7, height: 7, borderRadius: 4 },
  liveText: { fontSize: 11, fontWeight: '700', color: '#16a34a', letterSpacing: 1 },
  pollingText: { fontSize: 12 },
  summaryRow: { maxHeight: 80 },
  summaryContent: { paddingHorizontal: 12, paddingVertical: 10, gap: 8 },
  summaryCard: {
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    minWidth: 80,
  },
  summaryValue: { fontSize: 22, fontWeight: '700' },
  summaryLabel: { fontSize: 11, marginTop: 2 },
  controls: { paddingHorizontal: 12, paddingVertical: 8 },
  filterChip: {
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 14,
    backgroundColor: '#f1f5f9',
    marginRight: 6,
  },
  filterText: { fontSize: 12, fontWeight: '500' },
  sortDivider: {
    width: 1,
    backgroundColor: '#e2e8f0',
    marginHorizontal: 4,
    height: 24,
    alignSelf: 'center',
  },
  listContent: { padding: 12, gap: 8, paddingBottom: 32 },
  merchantCard: { borderRadius: 10, padding: 12, borderWidth: 1 },
  merchantHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 10 },
  statusDot: { marginRight: 6 },
  merchantName: { flex: 1, fontSize: 14, fontWeight: '600' },
  merchantCity: { fontSize: 12, marginLeft: 6 },
  merchantStats: { flexDirection: 'row', justifyContent: 'space-between' },
  stat: { alignItems: 'center', gap: 2 },
  statValue: { fontSize: 15, fontWeight: '700' },
  statLabel: { fontSize: 10 },
  emptyState: { alignItems: 'center', paddingVertical: 48, gap: 12 },
  emptyText: { fontSize: 14 },
  updatedAt: { textAlign: 'center', fontSize: 11, paddingVertical: 12 },
});
