import { StyleSheet } from 'react-native';
import { Colors } from '@/constants/Colors';

export const styles = StyleSheet.create({
  container: { flex: 1 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  headerTitle: { fontSize: 20, fontWeight: '700' },
  headerSubtitle: { fontSize: 13, marginTop: 2 },
  backBtn: { padding: 4 },
  background: { flex: 1 },
  backgroundSecondary: { flex: 1 },
  card: { borderRadius: 12, padding: 16, marginHorizontal: 16, marginBottom: 12 },
  cardTopRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  cardLeftCol: { flex: 1 },
  cardRightCol: { alignItems: 'flex-end' },
  cardBottomRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 8,
  },
  amount: { fontSize: 18, fontWeight: '700' },
  dateText: { fontSize: 12 },
  bankAccount: { fontSize: 13, marginTop: 4 },
  detailLabel: { fontSize: 12 },
  detailRow: { flexDirection: 'row', gap: 8, marginTop: 4 },
  detailScroll: { marginTop: 8 },
  countBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 10 },
  countText: { fontSize: 11, fontWeight: '600' },
  actionButton: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 8 },
  actionButtonText: { fontSize: 13, fontWeight: '600' },
  approveButton: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 8 },
  border: { borderWidth: 1 },
  emptyState: { flex: 1, justifyContent: 'center', alignItems: 'center', paddingTop: 60 },
  emptyText: { fontSize: 16, fontWeight: '600', marginTop: 8 },
  filter: { paddingHorizontal: 16, marginBottom: 12 },
  userRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  userLabel: { fontSize: 12, color: Colors.light.mutedDark },
  userName: { fontSize: 12, fontWeight: '600', flex: 1 },
  statusBadge: { paddingHorizontal: 6, paddingVertical: 2, borderRadius: 4 },
  statusText: { fontSize: 10, fontWeight: '700', textTransform: 'uppercase' },
  modalContainer: { flex: 1, backgroundColor: Colors.light.backgroundSecondary },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderBottomWidth: 1,
  },
  modalTitle: { fontSize: 17, fontWeight: '700' },
  detailSection: { marginBottom: 16 },
  sectionTitle: { fontSize: 15, fontWeight: '700', marginBottom: 8 },
  detailValue: { fontSize: 14, fontWeight: '600' },
  txCard: { borderRadius: 8, padding: 10, borderWidth: 1, marginBottom: 8 },
  txCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 4,
  },
  txAmount: { fontSize: 15, fontWeight: '700' },
  txDescription: { fontSize: 12, color: Colors.light.mutedDark, marginTop: 2 },
  txDate: { fontSize: 11, color: Colors.light.secondaryText, marginTop: 4 },
  txBank: { fontSize: 11, color: Colors.light.secondaryText, marginTop: 2 },
  txActions: { flexDirection: 'row', gap: 8, marginTop: 8 },
  approveButtonStyled: {
    backgroundColor: Colors.light.success,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
  },
  rejectButton: {
    backgroundColor: Colors.light.error,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
  },
  overlayContainer: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  dialogBox: { width: '90%', maxWidth: 400, borderRadius: 16, padding: 20 },
  dialogTitle: { fontSize: 18, fontWeight: '700', marginBottom: 8 },
  dialogSubtext: { fontSize: 14, color: Colors.light.secondaryText, marginBottom: 16 },
  inputLabel: { fontSize: 13, fontWeight: '600', marginBottom: 4, marginTop: 8 },
  dialogInput: {
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: 14,
    marginBottom: 16,
  },
  dialogActions: { flexDirection: 'row', gap: 12, marginTop: 8 },
  dialogButton: { flex: 1, paddingVertical: 10, borderRadius: 8, alignItems: 'center' },
  dialogCancelButton: {
    backgroundColor: Colors.light.gray200,
    borderWidth: 1,
    borderColor: Colors.light.gray300,
  },
  dialogCancelText: { fontSize: 14, fontWeight: '600', color: Colors.light.gray700 },
  dialogTextArea: { minHeight: 80, textAlignVertical: 'top' },
  searchBar: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: Colors.light.gray200,
  },
  searchInput: {
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: 14,
  },
  searchTextInput: { flex: 1, fontSize: 14 },
  emptyBox: { alignItems: 'center', paddingVertical: 60 },
});
export const s = styles;
