import { StyleSheet } from 'react-native';
import { Colors } from '@/constants/Colors';

export const merchantsStyles = StyleSheet.create({
  container: { flex: 1 },
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  filtersContainer: { padding: 16, paddingBottom: 8 },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    borderRadius: 12,
    marginBottom: 12,
  },
  searchInput: { flex: 1, height: 44, marginLeft: 8, fontSize: 15 },
  statusFilters: { flexDirection: 'row', gap: 8 },
  filterChip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    minHeight: 36,
    justifyContent: 'center',
  },
  filterChipText: { fontSize: 13, fontWeight: '500' },
  listContent: { padding: 16, paddingTop: 8 },
  merchantCard: { padding: 16, borderRadius: 12, marginBottom: 12 },
  merchantHeader: { flexDirection: 'row', alignItems: 'center' },
  merchantAvatar: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: Colors.light.errorLight,
    justifyContent: 'center',
    alignItems: 'center',
  },
  merchantInfo: { flex: 1, marginLeft: 12 },
  businessName: { fontSize: 16, fontWeight: '600' },
  businessType: { fontSize: 13, marginTop: 2 },
  statusBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12 },
  statusText: { fontSize: 12, fontWeight: '600', textTransform: 'capitalize' },
  merchantDetails: { marginTop: 16, gap: 8 },
  detailRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  detailText: { fontSize: 13 },
  actionButtons: { flexDirection: 'row', marginTop: 16, gap: 8 },
  actionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    borderRadius: 8,
    gap: 4,
  },
  actionButtonText: { color: Colors.light.card, fontWeight: '600', fontSize: 14 },
  emptyContainer: { padding: 40, alignItems: 'center' },
  emptyText: { marginTop: 12, fontSize: 16 },
  modalOverlay: {
    flex: 1,
    backgroundColor: Colors.light.modalOverlay,
    justifyContent: 'center',
    padding: 20,
  },
  modalContent: { borderRadius: 16, padding: 20 },
  modalTitle: { fontSize: 18, fontWeight: '600', marginBottom: 16 },
  reasonInput: {
    borderWidth: 1,
    borderRadius: 8,
    padding: 12,
    minHeight: 80,
    textAlignVertical: 'top',
  },
  modalButtons: { flexDirection: 'row', marginTop: 16, gap: 12 },
  modalButton: { flex: 1, paddingVertical: 12, borderRadius: 8, alignItems: 'center' },
  modalButtonText: { fontWeight: '600' },
  suspendModalHeader: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 16 },
  detailModalOverlay: {
    flex: 1,
    backgroundColor: Colors.light.modalOverlay,
    justifyContent: 'flex-end',
  },
  detailModalContent: {
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    maxHeight: '85%',
  },
  detailModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  detailModalBody: { maxHeight: 450 },
  detailSection: { marginBottom: 20 },
  detailMerchantHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 16 },
  detailAvatar: {
    width: 64,
    height: 64,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  detailMerchantInfo: { flex: 1, marginLeft: 16 },
  detailMerchantName: { fontSize: 20, fontWeight: '600', marginBottom: 8 },
  infoCard: { borderRadius: 12, padding: 16 },
  infoRow: { flexDirection: 'row', alignItems: 'flex-start', paddingVertical: 8 },
  infoContent: { flex: 1, marginLeft: 12 },
  infoLabel: { fontSize: 12, marginBottom: 2 },
  infoValue: { fontSize: 14, fontWeight: '500' },
  sectionTitle: { fontSize: 16, fontWeight: '600', marginBottom: 12 },
  storeItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    borderRadius: 10,
    marginBottom: 8,
    gap: 10,
  },
  storeInfo: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  storeName: { fontSize: 14, fontWeight: '500' },
  storeStatus: { fontSize: 12, fontWeight: '600', textTransform: 'capitalize' },
  programBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 8,
    minWidth: 80,
    justifyContent: 'center',
  },
  programBadgeText: { fontSize: 11, fontWeight: '600' },
  walletLoading: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
    gap: 8,
  },
  walletLoadingText: { fontSize: 14 },
  walletCard: { flexDirection: 'row', alignItems: 'center', borderRadius: 12, padding: 16 },
  walletIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(255,255,255,0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  walletInfo: { flex: 1, marginLeft: 16 },
  walletLabel: { color: 'rgba(255,255,255,0.8)', fontSize: 13, marginBottom: 4 },
  walletBalance: { color: Colors.light.card, fontSize: 24, fontWeight: '700' },
  walletStatsRow: { flexDirection: 'row', gap: 8, marginTop: 12 },
  walletStatItem: { flex: 1, borderRadius: 10, padding: 10, alignItems: 'center' },
  walletStatLabel: { fontSize: 12, marginBottom: 4 },
  walletStatValue: { fontSize: 13, fontWeight: '600' },
  walletEmpty: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    padding: 20,
    gap: 8,
  },
  walletEmptyText: { fontSize: 14 },
  closeButton: { marginTop: 16, paddingVertical: 14, borderRadius: 12, alignItems: 'center' },
  closeButtonText: { color: Colors.light.card, fontWeight: '600', fontSize: 16 },
  liveBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#ECFDF5',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#22C55E',
  },
  liveDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: '#22C55E' },
  liveText: { fontSize: 12, fontWeight: '800', color: '#15803D', letterSpacing: 0.5 },
  createButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 12,
    marginBottom: 12,
  },
  createButtonText: { fontSize: 15, fontWeight: '600' },
});
