import { StyleSheet } from 'react-native';
import { Colors } from '@/constants/Colors';

export const ordersStyles = StyleSheet.create({
  container: { flex: 1 },
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  filtersContainer: { padding: 16, paddingBottom: 8 },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    borderRadius: 12,
    marginBottom: 12,
  },
  searchInput: { flex: 1, height: 44, marginLeft: 8, fontSize: 15 },
  statusFilters: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  filterChip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    minHeight: 36,
    justifyContent: 'center',
  },
  filterChipText: { fontSize: 13, fontWeight: '500' },
  listContent: { padding: 16, paddingTop: 8 },
  orderCard: { padding: 16, borderRadius: 12, marginBottom: 12 },
  orderHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  orderNumber: { fontSize: 16, fontWeight: '600' },
  storeName: { fontSize: 13, marginTop: 2 },
  productNames: { fontSize: 12, marginTop: 2, fontStyle: 'italic' },
  statusBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12 },
  statusText: { fontSize: 11, fontWeight: '600', textTransform: 'capitalize' },
  orderDetails: { marginTop: 12, gap: 6 },
  detailRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  detailText: { fontSize: 13 },
  orderFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: Colors.light.border,
  },
  totalLabel: { fontSize: 12 },
  totalAmount: { fontSize: 18, fontWeight: '700', marginTop: 2 },
  paymentInfo: { alignItems: 'flex-end' },
  paymentBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 8, marginBottom: 4 },
  paymentStatusText: { fontSize: 11, fontWeight: '600', textTransform: 'capitalize' },
  deliveryType: { fontSize: 11, textTransform: 'capitalize' },
  feeBreakdown: { marginTop: 12, paddingTop: 12, borderTopWidth: 1 },
  feeRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 4 },
  feeLabel: { fontSize: 12 },
  feeValue: { fontSize: 12, fontWeight: '600' },
  actionButtons: { flexDirection: 'row', marginTop: 12, gap: 8 },
  actionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    borderRadius: 8,
    gap: 4,
  },
  actionButtonText: { color: Colors.light.card, fontWeight: '600', fontSize: 13 },
  emptyContainer: { padding: 40, alignItems: 'center' },
  emptyText: { marginTop: 12, fontSize: 16 },
  modalOverlay: { flex: 1, backgroundColor: Colors.light.modalOverlay, justifyContent: 'flex-end' },
  modalContent: {
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    maxHeight: '80%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalTitle: { fontSize: 18, fontWeight: '600' },
  modalBody: { maxHeight: 400 },
  sectionTitle: { fontSize: 14, fontWeight: '600', marginBottom: 12 },
  itemRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8 },
  itemName: { fontSize: 14, flex: 1 },
  itemPrice: { fontSize: 14 },
  totalSection: { marginTop: 16, paddingTop: 16, borderTopWidth: 1 },
  totalRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8 },
  totalValue: { fontSize: 14 },
  totalLabelBold: { fontSize: 16, fontWeight: '600' },
  totalValueBold: { fontSize: 16, fontWeight: '700' },
  closeButton: { marginTop: 20, paddingVertical: 14, borderRadius: 12, alignItems: 'center' },
  closeButtonText: { color: Colors.light.card, fontWeight: '600', fontSize: 16 },
  reasonModalOverlay: {
    flex: 1,
    backgroundColor: Colors.light.modalOverlay,
    justifyContent: 'center',
    padding: 20,
  },
  reasonModalContent: { borderRadius: 16, padding: 20 },
  reasonModalHeader: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 16 },
  reasonModalTitle: { fontSize: 18, fontWeight: '600' },
  reasonInput: {
    borderWidth: 1,
    borderRadius: 8,
    padding: 12,
    minHeight: 80,
    textAlignVertical: 'top',
  },
  reasonModalButtons: { flexDirection: 'row', marginTop: 16, gap: 12 },
  reasonModalButton: { flex: 1, paddingVertical: 12, borderRadius: 8, alignItems: 'center' },
  reasonModalButtonText: { fontWeight: '600' },
  statusOption: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 14,
    borderRadius: 12,
    borderWidth: 1,
    gap: 10,
  },
  statusDot: { width: 10, height: 10, borderRadius: 5 },
  statusOptionText: { flex: 1, fontSize: 15, fontWeight: '500', textTransform: 'capitalize' },
});
