import { StyleSheet } from 'react-native';
import { Colors } from '@/constants/Colors';

export const s = StyleSheet.create({
  container: { flex: 1 },
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    gap: 10,
  },
  headerTitle: { fontSize: 18, fontWeight: '700', flex: 1 },
  createBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    gap: 4,
  },
  createBtnText: { color: '#FFFFFF', fontWeight: '600', fontSize: 13 },
  tabsContainer: { flexDirection: 'row', paddingHorizontal: 16, marginBottom: 8, gap: 8 },
  tab: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: 'center',
    backgroundColor: '#E2E8F0',
  },
  tabText: { fontSize: 14, fontWeight: '600' },
  listContent: { padding: 16, paddingTop: 8 },
  card: {
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
  },
  cardHeader: { flexDirection: 'row', alignItems: 'center' },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardInfo: { flex: 1, marginLeft: 12 },
  pollTitle: { fontSize: 15, fontWeight: '600' },
  subtitle: { fontSize: 12, marginTop: 2 },
  badges: { flexDirection: 'row', gap: 4 },
  badge: { paddingHorizontal: 6, paddingVertical: 2, borderRadius: 6 },
  optionsPreview: { marginTop: 12 },
  optionRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 6, position: 'relative' },
  optionBar: { position: 'absolute', left: 0, top: 0, bottom: 0, borderRadius: 4 },
  optionText: { flex: 1, fontSize: 13, paddingVertical: 6, paddingHorizontal: 8 },
  optionCount: { fontSize: 12, fontWeight: '600', paddingRight: 4 },
  moreOptions: { fontSize: 11, marginTop: 2 },
  dateRow: { flexDirection: 'row', alignItems: 'center', marginTop: 8, gap: 4 },
  dateText: { fontSize: 11 },
  actionButtons: { flexDirection: 'row', marginTop: 10, gap: 8 },
  smallButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
    gap: 4,
  },
  smallButtonText: { fontWeight: '600', fontSize: 12 },
  emptyContainer: { padding: 40, alignItems: 'center' },
  emptyText: { marginTop: 12, fontSize: 16 },
  // Create modal
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    padding: 20,
  },
  createModalContent: { borderRadius: 16, padding: 20, maxHeight: '85%' },
  detailModalContent: { borderRadius: 16, padding: 20, maxHeight: '85%' },
  modalTitle: { fontSize: 18, fontWeight: '700', marginBottom: 16 },
  fieldLabel: { fontSize: 12, fontWeight: '600', marginBottom: 6, marginTop: 12 },
  input: {
    borderWidth: 1,
    borderRadius: 8,
    padding: 12,
    fontSize: 14,
  },
  multilineInput: { minHeight: 60, textAlignVertical: 'top' },
  optionInputRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 8, gap: 4 },
  removeOptionBtn: { padding: 4 },
  addOptionBtn: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingVertical: 6 },
  addOptionText: { fontSize: 13, fontWeight: '500' },
  switchRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 16,
  },
  switchLabel: { fontSize: 14, fontWeight: '500' },
  modalButtons: { flexDirection: 'row', marginTop: 20, gap: 12 },
  modalButton: { flex: 1, paddingVertical: 12, borderRadius: 8, alignItems: 'center' },
  modalButtonText: { fontWeight: '600' },
  // Detail modal
  detailDescription: { fontSize: 14, lineHeight: 20, marginBottom: 8 },
  detailStats: { flexDirection: 'row', marginTop: 12, gap: 8 },
  detailStat: { flex: 1, alignItems: 'center', padding: 10, borderRadius: 8 },
  detailStatValue: { fontSize: 18, fontWeight: '700' },
  detailStatLabel: { fontSize: 11, marginTop: 2 },
  resultRow: { marginBottom: 12 },
  resultInfo: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 4 },
  resultText: { fontSize: 13, fontWeight: '500', flex: 1 },
  resultCount: { fontSize: 12 },
  resultBarBg: { height: 8, borderRadius: 4, overflow: 'hidden' },
  resultBarFill: { height: '100%', borderRadius: 4 },
  detailDateRow: { flexDirection: 'row', alignItems: 'center', marginTop: 16, gap: 4 },
  closeDetailBtn: { paddingVertical: 12, borderRadius: 8, alignItems: 'center', marginTop: 12 },
});
