import { StyleSheet } from 'react-native';
import { Colors } from '@/constants/Colors';

export const styles = StyleSheet.create({
  container: { flex: 1 },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
  },
  headerTitle: { fontSize: 20, fontWeight: '700' },
  headerRight: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  headerContent: { flex: 1 },
  pendingBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 12 },
  pendingBadgeText: { fontSize: 12, fontWeight: '700', color: '#fff' },
  tabBar: { flexDirection: 'row', borderBottomWidth: 1, paddingHorizontal: 12 },
  tabBarContent: { flexDirection: 'row', gap: 8, paddingVertical: 8 },
  tab: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 16 },
  tabText: { fontSize: 13, fontWeight: '600' },
  tabBadge: {
    marginLeft: 4,
    paddingHorizontal: 6,
    paddingVertical: 1,
    borderRadius: 10,
    minWidth: 20,
    alignItems: 'center',
  },
  tabBadgeText: { fontSize: 10, fontWeight: '700', color: '#fff' },
  filterRow: { flexDirection: 'row', gap: 8, paddingHorizontal: 16, paddingVertical: 10 },
  platformFilters: { flexDirection: 'row', gap: 8 },
  platformChip: { paddingHorizontal: 10, paddingVertical: 5, borderRadius: 14, borderWidth: 1 },
  platformChipText: { fontSize: 12, fontWeight: '600' },
  submissionCard: {
    borderRadius: 12,
    padding: 14,
    marginHorizontal: 16,
    marginBottom: 10,
    borderWidth: 1,
  },
  selectButton: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 6 },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  submissionContent: { flexDirection: 'row', gap: 10 },
  headerRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 8 },
  username: { fontSize: 14, fontWeight: '700' },
  platformBadge: { paddingHorizontal: 6, paddingVertical: 2, borderRadius: 4 },
  platformBadgeText: { fontSize: 10, fontWeight: '700', textTransform: 'uppercase' },
  campaignName: { fontSize: 12, fontWeight: '600', marginTop: 2 },
  postUrl: { fontSize: 11, marginTop: 4, textDecorationLine: 'underline' },
  screenshotPlaceholder: { borderRadius: 8, overflow: 'hidden', marginTop: 8 },
  screenshotText: { fontSize: 11, color: '#9CA3AF', textAlign: 'center', padding: 16 },
  actionButtons: { flexDirection: 'row', gap: 8, marginTop: 10 },
  approveButton: { flex: 1, paddingVertical: 8, borderRadius: 8, alignItems: 'center' },
  buttonText: { fontSize: 13, fontWeight: '700' },
  rejectButton: { flex: 1, paddingVertical: 8, borderRadius: 8, alignItems: 'center' },
  rejectionBox: { marginTop: 8, padding: 10, borderRadius: 8, borderWidth: 1 },
  rejectionText: { fontSize: 12, fontWeight: '600', color: Colors.light.error },
  approvedBox: { marginTop: 8, padding: 10, borderRadius: 8 },
  approvedText: { fontSize: 12, fontWeight: '600', color: Colors.light.success },
  centerContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', gap: 12 },
  emptyText: { fontSize: 15, fontWeight: '600' },
  listContent: { paddingBottom: 100 },
  emptyContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', paddingTop: 60 },
  bulkActionBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderBottomWidth: 1,
  },
  bulkActionText: { fontSize: 13, fontWeight: '600', flex: 1 },
  bulkActionButtons: { flexDirection: 'row', gap: 8 },
  bulkApproveButton: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 8 },
  bulkRejectButton: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 8 },
  bulkActionButtonText: { fontSize: 13, fontWeight: '700' },
  analyticsContainer: { padding: 16 },
  analyticsTitle: { fontSize: 16, fontWeight: '700', marginBottom: 12 },
  analyticsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  analyticsCard: { width: '47%', borderRadius: 12, padding: 14, alignItems: 'center', gap: 4 },
  analyticsLabel: { fontSize: 11, textAlign: 'center' },
  analyticsValue: { fontSize: 18, fontWeight: '800' },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
  modalContent: {
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    maxHeight: '90%',
  },
  modalTitle: { fontSize: 18, fontWeight: '700', marginBottom: 4 },
  modalSubtitle: { fontSize: 13, color: Colors.light.secondaryText, marginBottom: 16 },
  rejectionInput: {
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: 14,
    minHeight: 80,
    textAlignVertical: 'top',
  },
  modalActions: { flexDirection: 'row', gap: 12, marginTop: 16 },
  modalButton: { flex: 1, paddingVertical: 12, borderRadius: 10, alignItems: 'center' },
  modalButtonText: { fontSize: 15, fontWeight: '700' },
});
export const s = styles;
