import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1 },
  background: { flex: 1 },
  backgroundSecondary: { flex: 1 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  headerTitle: { fontSize: 20, fontWeight: '700' },
  periodRow: { flexDirection: 'row', gap: 8, paddingHorizontal: 16, paddingVertical: 12 },
  periodBtn: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 8, borderWidth: 1 },
  periodBtnActive: { backgroundColor: '#1E3A5F', borderColor: '#1E3A5F' },
  periodBtnText: { fontSize: 13, fontWeight: '600' },
  periodBtnTextActive: { color: '#fff' },
  heroCard: { borderRadius: 16, padding: 20, marginHorizontal: 16, marginTop: 4, marginBottom: 16 },
  heroTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  heroLabel: { fontSize: 13, fontWeight: '600' },
  heroValue: { fontSize: 28, fontWeight: '800', marginTop: 4 },
  heroSub: { fontSize: 12, marginTop: 8 },
  growthBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 20,
  },
  growthUp: { backgroundColor: '#dcfce7' },
  growthDown: { backgroundColor: '#fee2e2' },
  growthText: { fontSize: 12, fontWeight: '700' },
  statsRow: { flexDirection: 'row', gap: 8, paddingHorizontal: 16, marginBottom: 16 },
  statCard: { flex: 1, borderRadius: 12, padding: 12, alignItems: 'center', gap: 4 },
  statValue: { fontSize: 14, fontWeight: '800' },
  statLabel: { fontSize: 10, textAlign: 'center' },
  errorBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    padding: 16,
    marginHorizontal: 16,
    borderRadius: 12,
    marginBottom: 12,
  },
  errorText: { fontSize: 13, flex: 1 },
  section: { paddingHorizontal: 16, marginBottom: 16 },
  sectionTitle: { fontSize: 17, fontWeight: '700', marginBottom: 12 },
  verticalCard: { borderRadius: 12, padding: 16, marginHorizontal: 16, marginBottom: 12 },
  verticalHeader: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 12 },
  iconCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  verticalName: { fontSize: 15, fontWeight: '600', flex: 1 },
  verticalShare: { fontSize: 12, fontWeight: '600' },
  verticalRevenue: { fontSize: 18, fontWeight: '700' },
  inlineGrowth: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  metricsRow: { flexDirection: 'row', gap: 16, marginTop: 8 },
  metric: { alignItems: 'flex-start' },
  metricValue: { fontSize: 14, fontWeight: '700' },
  metricLabel: { fontSize: 11, marginTop: 2 },
  barTrack: { height: 8, borderRadius: 4, overflow: 'hidden', marginTop: 8 },
  barFill: { height: '100%', borderRadius: 4 },
  card: { borderRadius: 12, padding: 16, marginHorizontal: 16, marginBottom: 12 },
  emptyBox: { padding: 20, alignItems: 'center' },
  emptyText: { fontSize: 16, fontWeight: '600', marginTop: 8 },
  emptyTitle: { fontSize: 14 },
  emptyContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', paddingTop: 60 },
  emptyMessage: { fontSize: 16, fontWeight: '600', marginTop: 8 },
  retryText: { fontSize: 13, fontWeight: '600', textDecorationLine: 'underline' },
  filter: { paddingHorizontal: 16, marginBottom: 12 },
});
export const s = styles;
