import { StyleSheet } from 'react-native';
import { Colors } from '@/constants/Colors';

export const s = StyleSheet.create({
  container: { flex: 1 },
  centerContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 12,
    padding: 24,
  },
  loadingText: { fontSize: 14, marginTop: 8 },
  errorText: { fontSize: 14, textAlign: 'center', marginTop: 8 },
  retryButton: {
    backgroundColor: Colors.light.info,
    borderRadius: 8,
    paddingHorizontal: 20,
    paddingVertical: 10,
    marginTop: 12,
  },
  retryButtonText: { color: Colors.light.card, fontWeight: '600' },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
  },
  headerTitle: { fontSize: 18, fontWeight: '700' },
  headerActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  headerBtn: { padding: 8 },
  saveButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.light.info,
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 8,
    gap: 4,
  },
  saveButtonDisabled: { opacity: 0.5 },
  saveButtonText: { color: Colors.light.card, fontWeight: '600', fontSize: 13 },
  dirtyBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.light.warningLight,
    paddingHorizontal: 16,
    paddingVertical: 8,
    gap: 6,
  },
  dirtyText: { color: Colors.light.warningDeep, fontSize: 12, fontWeight: '500' },
  scrollView: { flex: 1 },
  scrollContent: { padding: 16, paddingBottom: 100, gap: 12 },
  card: { borderRadius: 12, borderWidth: 1, overflow: 'hidden' },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 8,
  },
  cardTitle: { flex: 1, fontSize: 15, fontWeight: '600' },
  cardBody: { paddingHorizontal: 14, paddingVertical: 12, borderTopWidth: 1 },
  fieldRow: { marginBottom: 10 },
  fieldLabel: { fontSize: 12, fontWeight: '500', marginBottom: 4 },
  fieldInput: {
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 14,
  },
  switchRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 10, gap: 8 },
  subLabel: { fontSize: 12, fontWeight: '600', marginBottom: 6, textTransform: 'uppercase' },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginBottom: 10 },
  chip: { borderWidth: 1, borderRadius: 16, paddingHorizontal: 12, paddingVertical: 6 },
  chipText: { fontSize: 12, fontWeight: '500' },
  dayRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 8,
    borderBottomWidth: 0.5,
  },
  dayInfo: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  dayName: { fontSize: 13, fontWeight: '500', width: 80 },
  timeRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  timeInput: {
    borderWidth: 1,
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
    fontSize: 13,
    width: 60,
    textAlign: 'center',
  },
  listItemRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 8 },
  smallInput: {
    borderWidth: 1,
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 6,
    fontSize: 13,
    width: 110,
  },
  addButton: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingVertical: 8 },
  addButtonText: { color: Colors.light.info, fontSize: 13, fontWeight: '500' },
  itemCard: { borderWidth: 1, borderRadius: 8, padding: 12, marginBottom: 10 },
  itemHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  itemTitle: { fontSize: 14, fontWeight: '600' },
});
