import { StyleSheet } from 'react-native';
import { Colors } from '@/constants/Colors';

export const s = StyleSheet.create({
  container: { flex: 1 },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  pageTitle: { fontSize: 22, fontWeight: '700' },
  createButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: Colors.light.info,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 8,
  },
  createButtonText: { color: Colors.light.card, fontWeight: '600', fontSize: 14 },
  filterRow: { paddingHorizontal: 16, paddingBottom: 12, maxHeight: 48 },
  filterChip: {
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 20,
    backgroundColor: Colors.light.gray200,
    marginRight: 8,
  },
  filterChipActive: { backgroundColor: Colors.light.info },
  filterChipText: { fontSize: 13, fontWeight: '500', color: Colors.light.mutedDark },
  filterChipTextActive: { color: Colors.light.card },
  loadingCenter: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  listContent: { padding: 16, gap: 12 },
  emptyContainer: { alignItems: 'center', paddingTop: 60, gap: 12 },
  emptyText: { fontSize: 16, color: Colors.light.muted },
  card: {
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.light.gray200,
    gap: 8,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  cardTitle: { fontSize: 16, fontWeight: '600', flex: 1, marginRight: 8 },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  statusDot: { width: 6, height: 6, borderRadius: 3 },
  statusText: { fontSize: 11, fontWeight: '600' },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flexWrap: 'wrap',
  },
  chip: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 6 },
  chipText: { fontSize: 11, fontWeight: '600' },
  metaText: { fontSize: 12, color: Colors.light.mutedDark },
  dateRow: { marginTop: 2 },
  dateText: { fontSize: 12, color: Colors.light.muted },
  cardActions: {
    flexDirection: 'row',
    gap: 16,
    borderTopWidth: 1,
    borderTopColor: Colors.light.backgroundSecondary,
    paddingTop: 8,
    marginTop: 4,
  },
  actionBtn: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  actionText: { fontSize: 13, fontWeight: '500' },
  pagination: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 16,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: Colors.light.gray200,
  },
  pageBtn: {
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: Colors.light.infoLight,
    justifyContent: 'center',
    alignItems: 'center',
  },
  pageBtnDisabled: { backgroundColor: Colors.light.backgroundSecondary },
  pageInfo: { fontSize: 14, color: Colors.light.mutedDark },
  // Modal
  modalContainer: { flex: 1 },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: Colors.light.gray200,
  },
  modalTitle: { fontSize: 17, fontWeight: '600' },
  saveText: { fontSize: 16, fontWeight: '600', color: Colors.light.info },
  modalBody: { flex: 1 },
  modalBodyContent: { padding: 16, gap: 4, paddingBottom: 40 },
  fieldLabel: { fontSize: 13, fontWeight: '600', marginBottom: 6, marginTop: 12 },
  input: {
    borderWidth: 1,
    borderColor: Colors.light.gray300,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 15,
  },
  textArea: {
    borderWidth: 1,
    borderColor: Colors.light.gray300,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 15,
    minHeight: 80,
  },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  selectChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: Colors.light.gray300,
  },
  selectChipActive: { backgroundColor: Colors.light.infoLight, borderColor: Colors.light.info },
  selectChipText: { fontSize: 13, fontWeight: '500', color: Colors.light.mutedDark },
  numberRow: { flexDirection: 'row', gap: 12 },
  numberField: { flex: 1 },
  // Detail modal
  detailName: { fontSize: 22, fontWeight: '700', marginBottom: 8 },
  detailDescription: { fontSize: 14, lineHeight: 20, marginBottom: 12 },
  detailGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 16,
    marginBottom: 16,
  },
  detailCell: {
    width: '46%',
    padding: 12,
    borderRadius: 8,
    backgroundColor: Colors.light.backgroundSecondary,
  },
  detailLabel: { fontSize: 11, color: Colors.light.mutedDark, marginBottom: 4 },
  detailValue: { fontSize: 16, fontWeight: '600' },
  detailSectionTitle: { fontSize: 16, fontWeight: '700', marginTop: 20, marginBottom: 8 },
  prizeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: Colors.light.backgroundSecondary,
  },
  prizeRank: { fontSize: 14, fontWeight: '700', color: Colors.light.warning, width: 30 },
  prizeCoins: { fontSize: 14, fontWeight: '600' },
  prizeDesc: { fontSize: 12, color: Colors.light.mutedDark },
  participantRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: Colors.light.backgroundSecondary,
  },
  participantRank: { fontSize: 13, fontWeight: '600', color: Colors.light.mutedDark, width: 28 },
  participantName: { fontSize: 14, fontWeight: '500', flex: 1 },
  participantScore: { fontSize: 13, fontWeight: '600', color: Colors.light.info },
  participantGames: { fontSize: 12, color: Colors.light.muted },
  // Reactivate modal
  reactivateOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  reactivateCard: {
    width: '100%',
    maxWidth: 400,
    borderRadius: 16,
    padding: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  reactivateTitle: {
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 4,
  },
  reactivateSubtitle: {
    fontSize: 14,
    color: Colors.light.mutedDark,
  },
  reactivateNote: {
    fontSize: 12,
    color: Colors.light.warning,
    marginTop: 12,
    lineHeight: 18,
    backgroundColor: Colors.light.warningLight,
    padding: 10,
    borderRadius: 8,
  },
  reactivateActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 12,
    marginTop: 20,
  },
  reactivateCancelBtn: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
    backgroundColor: Colors.light.backgroundSecondary,
  },
  reactivateCancelText: {
    fontSize: 14,
    fontWeight: '600',
    color: Colors.light.mutedDark,
  },
  reactivateConfirmBtn: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 8,
    backgroundColor: Colors.light.warning,
  },
  reactivateConfirmText: {
    fontSize: 14,
    fontWeight: '600',
    color: Colors.light.card,
  },
});
