import { StyleSheet } from 'react-native';

/** Shared modal styles used by both SponsorFormModal and SponsorFundModal */
export const sharedModalStyles = StyleSheet.create({
  modalContainer: { flex: 1 },
  modalHeader: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingHorizontal: 16, paddingVertical: 12, borderBottomWidth: 1,
  },
  modalCloseBtn: { padding: 4 },
  modalTitle: { fontSize: 17, fontWeight: '600', flex: 1, textAlign: 'center' },
  modalSaveBtn: {
    paddingHorizontal: 16, paddingVertical: 8, borderRadius: 8, minWidth: 60, alignItems: 'center',
  },
  modalSaveBtnText: { fontWeight: '600', fontSize: 14 },
  formScroll: { flex: 1 },
  formContent: { padding: 16, paddingBottom: 40 },
  formGroup: { marginBottom: 16 },
  formLabel: { fontSize: 13, fontWeight: '600', marginBottom: 6 },
  formInput: { borderWidth: 1, borderRadius: 10, paddingHorizontal: 14, paddingVertical: 12, fontSize: 14 },
  textArea: { minHeight: 80, textAlignVertical: 'top' },
  formRow: { flexDirection: 'row', marginBottom: 0 },
  formSeparator: { height: 1, marginVertical: 16 },
  formSectionTitle: { fontSize: 16, fontWeight: '700', marginBottom: 14 },
  selectRow: { flexDirection: 'row', gap: 6, flexWrap: 'wrap' },
  selectChip: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 10, borderWidth: 1 },
  selectChipText: { fontSize: 12, fontWeight: '600' },
  fundSponsorInfo: {
    flexDirection: 'row', alignItems: 'center', padding: 14, borderRadius: 12, borderWidth: 1, marginBottom: 16, gap: 12,
  },
  fundSponsorDetails: { flex: 1 },
  fundSponsorName: { fontSize: 16, fontWeight: '700' },
  fundSponsorCoin: { fontSize: 12, marginTop: 2 },
  budgetLoadingContainer: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: 20, gap: 8 },
  budgetLoadingText: { fontSize: 13 },
  budgetSummary: { borderRadius: 12, borderWidth: 1, padding: 14, marginBottom: 16 },
  budgetSummaryTitle: { fontSize: 15, fontWeight: '700', marginBottom: 12 },
  budgetGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 0 },
  budgetGridItem: { width: '50%', paddingVertical: 6 },
  budgetGridLabel: { fontSize: 11, fontWeight: '500', marginBottom: 2 },
  budgetGridValue: { fontSize: 16, fontWeight: '700' },
  fundFormContainer: { borderRadius: 12, borderWidth: 1, padding: 14, marginBottom: 16 },
  fundFormTitle: { fontSize: 15, fontWeight: '700', marginBottom: 14 },
  fundNowBtn: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
    paddingVertical: 12, borderRadius: 10, gap: 8, marginTop: 4,
  },
  fundNowBtnText: { fontWeight: '700', fontSize: 15 },
  ledgerContainer: { borderRadius: 12, borderWidth: 1, padding: 14, marginBottom: 16 },
  ledgerTitle: { fontSize: 15, fontWeight: '700', marginBottom: 12 },
  ledgerEntry: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 10 },
  ledgerEntryLeft: { flexDirection: 'row', alignItems: 'center', flex: 1, gap: 10 },
  ledgerIcon: { width: 32, height: 32, borderRadius: 8, justifyContent: 'center', alignItems: 'center' },
  ledgerEntryInfo: { flex: 1 },
  ledgerEntryType: { fontSize: 13, fontWeight: '600' },
  ledgerEntryDesc: { fontSize: 11, marginTop: 1 },
  ledgerEntryDate: { fontSize: 10, marginTop: 2 },
  ledgerEntryAmount: { fontSize: 14, fontWeight: '700', marginLeft: 8 },
});
