/**
 * DOOH - Screen Management Service
 * Manages screens in the network
 */

import {
  Screen,
  ScreenType,
  ScreenStatus,
  ScreenOSConfig,
  ContentUpdate,
  Playlist,
  ScreenHeartbeat
} from '../types'

/**
 * Screen Manager - Manages DOOH network screens
 */
export class ScreenManager {
  private screens: Map<string, Screen> = new Map()

  /**
   * Register a new screen
   */
  register(screen: Screen): void {
    this.screens.set(screen.id, screen)
  }

  /**
   * Get screen by ID
   */
  get(screenId: string): Screen | undefined {
    return this.screens.get(screenId)
  }

  /**
   * Update screen status
   */
  updateStatus(screenId: string, status: ScreenStatus): void {
    const screen = this.screens.get(screenId)
    if (screen) {
      screen.status = status
      screen.last_seen = new Date()
      this.screens.set(screenId, screen)
    }
  }

  /**
   * Get screens by criteria
   */
  query(filter: ScreenFilter): Screen[] {
    return Array.from(this.screens.values()).filter(screen => {
      if (filter.type && screen.type !== filter.type) return false
      if (filter.city && screen.location.city !== filter.city) return false
      if (filter.status && screen.status !== filter.status) return false
      if (filter.owner_type && screen.owner_type !== filter.owner_type) return false
      return true
    })
  }

  /**
   * Get screens for playlist update
   */
  getForPlaylistUpdate(): Screen[] {
    return this.query({ status: 'active' })
  }

  /**
   * Process screen heartbeat
   */
  processHeartbeat(heartbeat: ScreenHeartbeat): ContentUpdate | null {
    const screen = this.screens.get(heartbeat.screen_id)
    if (!screen) return null

    // Update screen status
    screen.last_heartbeat = heartbeat.timestamp
    screen.status = heartbeat.status
    this.screens.set(heartbeat.screen_id, screen)

    // Return content update if needed
    if (this.needsPlaylistUpdate(screen, heartbeat)) {
      return this.generateContentUpdate(screen)
    }

    return null
  }

  /**
   * Check if screen needs playlist update
   */
  private needsPlaylistUpdate(screen: Screen, heartbeat: ScreenHeartbeat): boolean {
    if (!screen.playlist_version) return true
    if (heartbeat.playlist_version !== screen.playlist_version) return true
    if (!screen.last_sync) return true

    const syncAge = Date.now() - screen.last_sync.getTime()
    const maxAge = 60 * 60 * 1000 // 1 hour
    return syncAge > maxAge
  }

  /**
   * Generate content update for screen
   */
  private generateContentUpdate(screen: Screen): ContentUpdate {
    return {
      screen_id: screen.id,
      playlist: {} as Playlist, // Would be generated by PlaylistService
      creatives: [], // Would be fetched
      config: this.getScreenConfig(),
      version: (screen.playlist_version || 0) + 1,
      timestamp: new Date()
    }
  }

  /**
   * Get screen OS configuration
   */
  private getScreenConfig(): ScreenOSConfig {
    return {
      server_url: process.env.DOOH_SERVER_URL || 'https://dooh.rezapp.com',
      api_key: process.env.DOOH_API_KEY || '',
      sync_interval: 300, // 5 minutes
      playlist_refresh: 300,
      heartbeat_interval: 60,
      offline_buffer_hours: 24
    }
  }

  /**
   * Get network statistics
   */
  getStats(): NetworkStats {
    const screens = Array.from(this.screens.values())

    return {
      total: screens.length,
      active: screens.filter(s => s.status === 'active').length,
      offline: screens.filter(s => s.status === 'offline').length,
      maintenance: screens.filter(s => s.status === 'maintenance').length,
      by_type: this.groupByType(screens),
      by_city: this.groupByCity(screens)
    }
  }

  private groupByType(screens: Screen[]): Record<ScreenType, number> {
    const groups: Partial<Record<ScreenType, number>> = {}
    for (const screen of screens) {
      groups[screen.type] = (groups[screen.type] || 0) + 1
    }
    return groups as Record<ScreenType, number>
  }

  private groupByCity(screens: Screen[]): Record<string, number> {
    const groups: Record<string, number> = {}
    for (const screen of screens) {
      groups[screen.location.city] = (groups[screen.location.city] || 0) + 1
    }
    return groups
  }
}

interface ScreenFilter {
  type?: ScreenType
  city?: string
  status?: ScreenStatus
  owner_type?: 'owned' | 'partner' | 'external'
}

interface NetworkStats {
  total: number
  active: number
  offline: number
  maintenance: number
  by_type: Record<ScreenType, number>
  by_city: Record<string, number>
}

export interface Screen extends Screen {
  last_heartbeat?: Date
  playlist_version?: number
  last_sync?: Date
}

/**
 * Factory function
 */
export function createScreenManager(): ScreenManager {
  return new ScreenManager()
}
